-- Built-in starter decks. Names: category · set. Order: sort_order.

INSERT INTO decks (name, owner_id, source_type, sort_order)
VALUES ('일본어 · 히라가나', NULL, 'BUILTIN', 10);

INSERT INTO cards (deck_id, front_text, back_text, sort_order)
SELECT d.id, v.front, v.back, v.ord
FROM decks d
CROSS JOIN (
    VALUES
        ('あ', '아', 1),
        ('い', '이', 2),
        ('う', '우', 3),
        ('え', '에', 4),
        ('お', '오', 5),
        ('か', '카', 6),
        ('き', '키', 7),
        ('く', '쿠', 8),
        ('け', '케', 9),
        ('こ', '코', 10),
        ('さ', '사', 11),
        ('し', '시', 12),
        ('す', '스', 13),
        ('せ', '세', 14),
        ('そ', '소', 15),
        ('た', '타', 16),
        ('ち', '치', 17),
        ('つ', '츠', 18),
        ('て', '테', 19),
        ('と', '토', 20),
        ('な', '나', 21),
        ('に', '니', 22),
        ('ぬ', '누', 23),
        ('ね', '네', 24),
        ('の', '노', 25),
        ('は', '하', 26),
        ('ひ', '히', 27),
        ('ふ', '후', 28),
        ('へ', '헤', 29),
        ('ほ', '호', 30),
        ('ま', '마', 31),
        ('み', '미', 32),
        ('む', '무', 33),
        ('め', '메', 34),
        ('も', '모', 35),
        ('や', '야', 36),
        ('ゆ', '유', 37),
        ('よ', '요', 38),
        ('ら', '라', 39),
        ('り', '리', 40),
        ('る', '루', 41),
        ('れ', '레', 42),
        ('ろ', '로', 43),
        ('わ', '와', 44),
        ('を', '오', 45),
        ('ん', '응', 46)
) AS v(front, back, ord)
WHERE d.name = '일본어 · 히라가나' AND d.source_type = 'BUILTIN';

INSERT INTO decks (name, owner_id, source_type, sort_order)
VALUES ('일본어 · 히라가나 탁음', NULL, 'BUILTIN', 20);

INSERT INTO cards (deck_id, front_text, back_text, sort_order)
SELECT d.id, v.front, v.back, v.ord
FROM decks d
CROSS JOIN (
    VALUES
        ('が', '가', 1),
        ('ぎ', '기', 2),
        ('ぐ', '구', 3),
        ('げ', '게', 4),
        ('ご', '고', 5),
        ('ざ', '자', 6),
        ('じ', '지', 7),
        ('ず', '즈', 8),
        ('ぜ', '제', 9),
        ('ぞ', '조', 10),
        ('だ', '다', 11),
        ('ぢ', '지', 12),
        ('づ', '즈', 13),
        ('で', '데', 14),
        ('ど', '도', 15),
        ('ば', '바', 16),
        ('び', '비', 17),
        ('ぶ', '부', 18),
        ('べ', '베', 19),
        ('ぼ', '보', 20),
        ('ぱ', '파', 21),
        ('ぴ', '피', 22),
        ('ぷ', '푸', 23),
        ('ぺ', '페', 24),
        ('ぽ', '포', 25)
) AS v(front, back, ord)
WHERE d.name = '일본어 · 히라가나 탁음' AND d.source_type = 'BUILTIN';

INSERT INTO decks (name, owner_id, source_type, sort_order)
VALUES ('일본어 · 히라가나 요음', NULL, 'BUILTIN', 30);

INSERT INTO cards (deck_id, front_text, back_text, sort_order)
SELECT d.id, v.front, v.back, v.ord
FROM decks d
CROSS JOIN (
    VALUES
        ('きゃ', '캬', 1),
        ('きゅ', '큐', 2),
        ('きょ', '쿄', 3),
        ('しゃ', '샤', 4),
        ('しゅ', '슈', 5),
        ('しょ', '쇼', 6),
        ('ちゃ', '챠', 7),
        ('ちゅ', '츄', 8),
        ('ちょ', '쵸', 9),
        ('にゃ', '냐', 10),
        ('にゅ', '뉴', 11),
        ('にょ', '뇨', 12),
        ('ひゃ', '햐', 13),
        ('ひゅ', '휴', 14),
        ('ひょ', '효', 15),
        ('みゃ', '먀', 16),
        ('みゅ', '뮤', 17),
        ('みょ', '묘', 18),
        ('りゃ', '랴', 19),
        ('りゅ', '류', 20),
        ('りょ', '료', 21),
        ('ぎゃ', '갸', 22),
        ('ぎゅ', '규', 23),
        ('ぎょ', '교', 24),
        ('じゃ', '쟈', 25),
        ('じゅ', '쥬', 26),
        ('じょ', '죠', 27),
        ('びゃ', '뱌', 28),
        ('びゅ', '뷰', 29),
        ('びょ', '뵤', 30),
        ('ぴゃ', '퍄', 31),
        ('ぴゅ', '퓨', 32),
        ('ぴょ', '표', 33)
) AS v(front, back, ord)
WHERE d.name = '일본어 · 히라가나 요음' AND d.source_type = 'BUILTIN';

INSERT INTO decks (name, owner_id, source_type, sort_order)
VALUES ('일본어 · 가타카나', NULL, 'BUILTIN', 40);

INSERT INTO cards (deck_id, front_text, back_text, sort_order)
SELECT d.id, v.front, v.back, v.ord
FROM decks d
CROSS JOIN (
    VALUES
        ('ア', '아', 1),
        ('イ', '이', 2),
        ('ウ', '우', 3),
        ('エ', '에', 4),
        ('オ', '오', 5),
        ('カ', '카', 6),
        ('キ', '키', 7),
        ('ク', '쿠', 8),
        ('ケ', '케', 9),
        ('コ', '코', 10),
        ('サ', '사', 11),
        ('シ', '시', 12),
        ('ス', '스', 13),
        ('セ', '세', 14),
        ('ソ', '소', 15),
        ('タ', '타', 16),
        ('チ', '치', 17),
        ('ツ', '츠', 18),
        ('テ', '테', 19),
        ('ト', '토', 20),
        ('ナ', '나', 21),
        ('ニ', '니', 22),
        ('ヌ', '누', 23),
        ('ネ', '네', 24),
        ('ノ', '노', 25),
        ('ハ', '하', 26),
        ('ヒ', '히', 27),
        ('フ', '후', 28),
        ('ヘ', '헤', 29),
        ('ホ', '호', 30),
        ('マ', '마', 31),
        ('ミ', '미', 32),
        ('ム', '무', 33),
        ('メ', '메', 34),
        ('モ', '모', 35),
        ('ヤ', '야', 36),
        ('ユ', '유', 37),
        ('ヨ', '요', 38),
        ('ラ', '라', 39),
        ('リ', '리', 40),
        ('ル', '루', 41),
        ('レ', '레', 42),
        ('ロ', '로', 43),
        ('ワ', '와', 44),
        ('ヲ', '오', 45),
        ('ン', '응', 46)
) AS v(front, back, ord)
WHERE d.name = '일본어 · 가타카나' AND d.source_type = 'BUILTIN';

INSERT INTO decks (name, owner_id, source_type, sort_order)
VALUES ('일본어 · 가타카나 탁음', NULL, 'BUILTIN', 50);

INSERT INTO cards (deck_id, front_text, back_text, sort_order)
SELECT d.id, v.front, v.back, v.ord
FROM decks d
CROSS JOIN (
    VALUES
        ('ガ', '가', 1),
        ('ギ', '기', 2),
        ('グ', '구', 3),
        ('ゲ', '게', 4),
        ('ゴ', '고', 5),
        ('ザ', '자', 6),
        ('ジ', '지', 7),
        ('ズ', '즈', 8),
        ('ゼ', '제', 9),
        ('ゾ', '조', 10),
        ('ダ', '다', 11),
        ('ヂ', '지', 12),
        ('ヅ', '즈', 13),
        ('デ', '데', 14),
        ('ド', '도', 15),
        ('バ', '바', 16),
        ('ビ', '비', 17),
        ('ブ', '부', 18),
        ('ベ', '베', 19),
        ('ボ', '보', 20),
        ('パ', '파', 21),
        ('ピ', '피', 22),
        ('プ', '푸', 23),
        ('ペ', '페', 24),
        ('ポ', '포', 25)
) AS v(front, back, ord)
WHERE d.name = '일본어 · 가타카나 탁음' AND d.source_type = 'BUILTIN';

INSERT INTO decks (name, owner_id, source_type, sort_order)
VALUES ('일본어 · 숫자', NULL, 'BUILTIN', 60);

INSERT INTO cards (deck_id, front_text, back_text, sort_order)
SELECT d.id, v.front, v.back, v.ord
FROM decks d
CROSS JOIN (
    VALUES
        ('一', '1 / 이치', 1),
        ('二', '2 / 니', 2),
        ('三', '3 / 산', 3),
        ('四', '4 / 욘', 4),
        ('五', '5 / 고', 5),
        ('六', '6 / 로쿠', 6),
        ('七', '7 / 나나', 7),
        ('八', '8 / 하치', 8),
        ('九', '9 / 큐', 9),
        ('十', '10 / 주', 10),
        ('十一', '11 / 주이치', 11),
        ('十二', '12 / 주니', 12),
        ('十三', '13 / 주산', 13),
        ('十四', '14 / 주욘', 14),
        ('十五', '15 / 주고', 15),
        ('十六', '16 / 주로쿠', 16),
        ('十七', '17 / 주나나', 17),
        ('十八', '18 / 주하치', 18),
        ('十九', '19 / 주큐', 19),
        ('二十', '20 / 니주', 20),
        ('三十', '30 / 산주', 21),
        ('四十', '40 / 욘주', 22),
        ('五十', '50 / 고주', 23),
        ('百', '100 / 햐쿠', 24),
        ('千', '1000 / 센', 25)
) AS v(front, back, ord)
WHERE d.name = '일본어 · 숫자' AND d.source_type = 'BUILTIN';

INSERT INTO decks (name, owner_id, source_type, sort_order)
VALUES ('지리 · 세계 수도', NULL, 'BUILTIN', 70);

INSERT INTO cards (deck_id, front_text, back_text, sort_order)
SELECT d.id, v.front, v.back, v.ord
FROM decks d
CROSS JOIN (
    VALUES
        (E'가나\nGhana', E'아크라\nAccra', 1),
        (E'가봉\nGabon', E'리브르빌\nLibreville', 2),
        (E'가이아나\nGuyana', E'조지타운\nGeorgetown', 3),
        (E'감비아\nGambia', E'반줄\nBanjul', 4),
        (E'과테말라\nGuatemala', E'과테말라시티\nGuatemala City', 5),
        (E'그레나다\nGrenada', E'세인트조지스\nSt. George''s', 6),
        (E'그리스\nGreece', E'아테네\nAthens', 7),
        (E'기니\nGuinea', E'코나크리\nConakry', 8),
        (E'기니비사우\nGuinea-Bissau', E'비사우\nBissau', 9),
        (E'나미비아\nNamibia', E'빈트후크\nWindhoek', 10),
        (E'나우루\nNauru', E'야렌\nYaren', 11),
        (E'나이지리아\nNigeria', E'아부자\nAbuja', 12),
        (E'남수단\nSouth Sudan', E'주바\nJuba', 13),
        (E'남아프리카공화국\nSouth Africa', E'프리토리아\nPretoria', 14),
        (E'네덜란드\nNetherlands', E'암스테르담\nAmsterdam', 15),
        (E'네팔\nNepal', E'카트만두\nKathmandu', 16),
        (E'노르웨이\nNorway', E'오슬로\nOslo', 17),
        (E'뉴질랜드\nNew Zealand', E'웰링턴\nWellington', 18),
        (E'니제르\nNiger', E'니아메\nNiamey', 19),
        (E'니카라과\nNicaragua', E'마나과\nManagua', 20),
        (E'대한민국\nSouth Korea', E'서울\nSeoul', 21),
        (E'덴마크\nDenmark', E'코펜하겐\nCopenhagen', 22),
        (E'도미니카공화국\nDominican Republic', E'산토도밍고\nSanto Domingo', 23),
        (E'도미니카연방\nDominica', E'로조\nRoseau', 24),
        (E'독일\nGermany', E'베를린\nBerlin', 25),
        (E'동티모르\nTimor-Leste', E'딜리\nDili', 26),
        (E'라오스\nLaos', E'비엔티안\nVientiane', 27),
        (E'라이베리아\nLiberia', E'몬로비아\nMonrovia', 28),
        (E'라트비아\nLatvia', E'리가\nRiga', 29),
        (E'러시아\nRussia', E'모스크바\nMoscow', 30),
        (E'레바논\nLebanon', E'베이루트\nBeirut', 31),
        (E'레소토\nLesotho', E'마세루\nMaseru', 32),
        (E'루마니아\nRomania', E'부쿠레슈티\nBucharest', 33),
        (E'룩셈부르크\nLuxembourg', E'룩셈부르크\nLuxembourg', 34),
        (E'르완다\nRwanda', E'키갈리\nKigali', 35),
        (E'리비아\nLibya', E'트리폴리\nTripoli', 36),
        (E'리투아니아\nLithuania', E'빌뉴스\nVilnius', 37),
        (E'리히텐슈타인\nLiechtenstein', E'파두츠\nVaduz', 38),
        (E'마다가스카르\nMadagascar', E'안타나나리보\nAntananarivo', 39),
        (E'마셜제도\nMarshall Islands', E'마주로\nMajuro', 40),
        (E'말라위\nMalawi', E'릴롱궤\nLilongwe', 41),
        (E'말레이시아\nMalaysia', E'쿠알라룸푸르\nKuala Lumpur', 42),
        (E'말리\nMali', E'바마코\nBamako', 43),
        (E'멕시코\nMexico', E'멕시코시티\nMexico City', 44),
        (E'모나코\nMonaco', E'모나코\nMonaco', 45),
        (E'모로코\nMorocco', E'라바트\nRabat', 46),
        (E'모리셔스\nMauritius', E'포트루이스\nPort Louis', 47),
        (E'모리타니\nMauritania', E'누악쇼트\nNouakchott', 48),
        (E'모잠비크\nMozambique', E'마푸토\nMaputo', 49),
        (E'몬테네그로\nMontenegro', E'포드고리차\nPodgorica', 50),
        (E'몰도바\nMoldova', E'키시너우\nChișinău', 51),
        (E'몰디브\nMaldives', E'말레\nMalé', 52),
        (E'몰타\nMalta', E'발레타\nValletta', 53),
        (E'몽골\nMongolia', E'울란바토르\nUlaanbaatar', 54),
        (E'미국\nUnited States', E'워싱턴 D.C.\nWashington, D.C.', 55),
        (E'미얀마\nMyanmar', E'네피도\nNaypyidaw', 56),
        (E'미크로네시아\nMicronesia', E'팔리키르\nPalikir', 57),
        (E'바누아투\nVanuatu', E'포트빌라\nPort Vila', 58),
        (E'바레인\nBahrain', E'마나마\nManama', 59),
        (E'바베이도스\nBarbados', E'브리지타운\nBridgetown', 60),
        (E'바티칸\nVatican City', E'바티칸\nVatican City', 61),
        (E'바하마\nBahamas', E'나소\nNassau', 62),
        (E'방글라데시\nBangladesh', E'다카\nDhaka', 63),
        (E'베냉\nBenin', E'포르토노보\nPorto-Novo', 64),
        (E'베네수엘라\nVenezuela', E'카라카스\nCaracas', 65),
        (E'베트남\nVietnam', E'하노이\nHanoi', 66),
        (E'벨기에\nBelgium', E'브뤼셀\nBrussels', 67),
        (E'벨라루스\nBelarus', E'민스크\nMinsk', 68),
        (E'벨리즈\nBelize', E'벨모판\nBelmopan', 69),
        (E'보스니아헤르체고비나\nBosnia and Herzegovina', E'사라예보\nSarajevo', 70),
        (E'보츠와나\nBotswana', E'가보로네\nGaborone', 71),
        (E'볼리비아\nBolivia', E'라파스\nLa Paz', 72),
        (E'부룬디\nBurundi', E'기테가\nGitega', 73),
        (E'부르키나파소\nBurkina Faso', E'와가두구\nOuagadougou', 74),
        (E'부탄\nBhutan', E'팀부\nThimphu', 75),
        (E'북마케도니아\nNorth Macedonia', E'스코페\nSkopje', 76),
        (E'북한\nNorth Korea', E'평양\nPyongyang', 77),
        (E'불가리아\nBulgaria', E'소피아\nSofia', 78),
        (E'브라질\nBrazil', E'브라질리아\nBrasília', 79),
        (E'브루나이\nBrunei', E'반다르스리브가완\nBandar Seri Begawan', 80),
        (E'사모아\nSamoa', E'아피아\nApia', 81),
        (E'사우디아라비아\nSaudi Arabia', E'리야드\nRiyadh', 82),
        (E'산마리노\nSan Marino', E'산마리노\nSan Marino', 83),
        (E'상투메프린시페\nSão Tomé and Príncipe', E'상투메\nSão Tomé', 84),
        (E'세네갈\nSenegal', E'다카르\nDakar', 85),
        (E'세르비아\nSerbia', E'베오그라드\nBelgrade', 86),
        (E'세이셸\nSeychelles', E'빅토리아\nVictoria', 87),
        (E'세인트루시아\nSaint Lucia', E'캐스트리스\nCastries', 88),
        (E'세인트빈센트그레나딘\nSaint Vincent and the Grenadines', E'킹스타운\nKingstown', 89),
        (E'세인트키츠네비스\nSaint Kitts and Nevis', E'바스테르\nBasseterre', 90),
        (E'소말리아\nSomalia', E'모가디슈\nMogadishu', 91),
        (E'솔로몬제도\nSolomon Islands', E'호니아라\nHoniara', 92),
        (E'수단\nSudan', E'하르툼\nKhartoum', 93),
        (E'수리남\nSuriname', E'파라마리보\nParamaribo', 94),
        (E'스리랑카\nSri Lanka', E'스리자야와르데네푸라코테\nSri Jayawardenepura Kotte', 95),
        (E'스웨덴\nSweden', E'스톡홀름\nStockholm', 96),
        (E'스위스\nSwitzerland', E'베른\nBern', 97),
        (E'스페인\nSpain', E'마드리드\nMadrid', 98),
        (E'슬로바키아\nSlovakia', E'브라티슬라바\nBratislava', 99),
        (E'슬로베니아\nSlovenia', E'류블랴나\nLjubljana', 100),
        (E'시리아\nSyria', E'다마스쿠스\nDamascus', 101),
        (E'시에라리온\nSierra Leone', E'프리타운\nFreetown', 102),
        (E'싱가포르\nSingapore', E'싱가포르\nSingapore', 103),
        (E'아랍에미리트\nUnited Arab Emirates', E'아부다비\nAbu Dhabi', 104),
        (E'아르메니아\nArmenia', E'예레반\nYerevan', 105),
        (E'아르헨티나\nArgentina', E'부에노스아이레스\nBuenos Aires', 106),
        (E'아이슬란드\nIceland', E'레이캬비크\nReykjavík', 107),
        (E'아이티\nHaiti', E'포르토프랭스\nPort-au-Prince', 108),
        (E'아일랜드\nIreland', E'더블린\nDublin', 109),
        (E'아제르바이잔\nAzerbaijan', E'바쿠\nBaku', 110),
        (E'아프가니스탄\nAfghanistan', E'카불\nKabul', 111),
        (E'안도라\nAndorra', E'안도라라베야\nAndorra la Vella', 112),
        (E'알바니아\nAlbania', E'티라나\nTirana', 113),
        (E'알제리\nAlgeria', E'알제\nAlgiers', 114),
        (E'앙골라\nAngola', E'루안다\nLuanda', 115),
        (E'앤티가바부다\nAntigua and Barbuda', E'세인트존스\nSaint John''s', 116),
        (E'에리트레아\nEritrea', E'아스마라\nAsmara', 117),
        (E'에스와티니\nEswatini', E'음바바네\nMbabane', 118),
        (E'에스토니아\nEstonia', E'탈린\nTallinn', 119),
        (E'에콰도르\nEcuador', E'키토\nQuito', 120),
        (E'에티오피아\nEthiopia', E'아디스아바바\nAddis Ababa', 121),
        (E'엘살바도르\nEl Salvador', E'산살바도르\nSan Salvador', 122),
        (E'영국\nUnited Kingdom', E'런던\nLondon', 123),
        (E'예멘\nYemen', E'사나\nSana''a', 124),
        (E'오만\nOman', E'무스카트\nMuscat', 125),
        (E'오스트리아\nAustria', E'빈\nVienna', 126),
        (E'온두라스\nHonduras', E'테구시갈파\nTegucigalpa', 127),
        (E'요르단\nJordan', E'암만\nAmman', 128),
        (E'우간다\nUganda', E'캄팔라\nKampala', 129),
        (E'우루과이\nUruguay', E'몬테비데오\nMontevideo', 130),
        (E'우즈베키스탄\nUzbekistan', E'타슈켄트\nTashkent', 131),
        (E'우크라이나\nUkraine', E'키이우\nKyiv', 132),
        (E'이라크\nIraq', E'바그다드\nBaghdad', 133),
        (E'이란\nIran', E'테헤란\nTehran', 134),
        (E'이스라엘\nIsrael', E'예루살렘\nJerusalem', 135),
        (E'이집트\nEgypt', E'카이로\nCairo', 136),
        (E'이탈리아\nItaly', E'로마\nRome', 137),
        (E'인도\nIndia', E'뉴델리\nNew Delhi', 138),
        (E'인도네시아\nIndonesia', E'자카르타\nJakarta', 139),
        (E'일본\nJapan', E'도쿄\nTokyo', 140),
        (E'자메이카\nJamaica', E'킹스턴\nKingston', 141),
        (E'잠비아\nZambia', E'루사카\nLusaka', 142),
        (E'적도기니\nEquatorial Guinea', E'말라보\nMalabo', 143),
        (E'조지아\nGeorgia', E'트빌리시\nTbilisi', 144),
        (E'중국\nChina', E'베이징\nBeijing', 145),
        (E'중앙아프리카공화국\nCentral African Republic', E'방기\nBangui', 146),
        (E'지부티\nDjibouti', E'지부티\nDjibouti', 147),
        (E'짐바브웨\nZimbabwe', E'하라레\nHarare', 148),
        (E'차드\nChad', E'은자메나\nN''Djamena', 149),
        (E'체코\nCzechia', E'프라하\nPrague', 150),
        (E'칠레\nChile', E'산티아고\nSantiago', 151),
        (E'카메룬\nCameroon', E'야운데\nYaoundé', 152),
        (E'카보베르데\nCabo Verde', E'프라이아\nPraia', 153),
        (E'카자흐스탄\nKazakhstan', E'아스타나\nAstana', 154),
        (E'카타르\nQatar', E'도하\nDoha', 155),
        (E'캄보디아\nCambodia', E'프놈펜\nPhnom Penh', 156),
        (E'캐나다\nCanada', E'오타와\nOttawa', 157),
        (E'케냐\nKenya', E'나이로비\nNairobi', 158),
        (E'코모로\nComoros', E'모로니\nMoroni', 159),
        (E'코소보\nKosovo', E'프리슈티나\nPristina', 160),
        (E'코스타리카\nCosta Rica', E'산호세\nSan José', 161),
        (E'코트디부아르\nCôte d''Ivoire', E'야무수크로\nYamoussoukro', 162),
        (E'콜롬비아\nColombia', E'보고타\nBogotá', 163),
        (E'콩고공화국\nRepublic of the Congo', E'브라자빌\nBrazzaville', 164),
        (E'콩고민주공화국\nDR Congo', E'킨샤사\nKinshasa', 165),
        (E'쿠바\nCuba', E'아바나\nHavana', 166),
        (E'쿠웨이트\nKuwait', E'쿠웨이트시티\nKuwait City', 167),
        (E'크로아티아\nCroatia', E'자그레브\nZagreb', 168),
        (E'키르기스스탄\nKyrgyzstan', E'비슈케크\nBishkek', 169),
        (E'키리바시\nKiribati', E'타라와\nTarawa', 170),
        (E'키프로스\nCyprus', E'니코시아\nNicosia', 171),
        (E'타지키스탄\nTajikistan', E'두샨베\nDushanbe', 172),
        (E'탄자니아\nTanzania', E'도도마\nDodoma', 173),
        (E'태국\nThailand', E'방콕\nBangkok', 174),
        (E'대만\nTaiwan', E'타이베이\nTaipei', 175),
        (E'튀르키예\nTürkiye', E'앙카라\nAnkara', 176),
        (E'토고\nTogo', E'로메\nLomé', 177),
        (E'통가\nTonga', E'누쿠알로파\nNuku''alofa', 178),
        (E'투르크메니스탄\nTurkmenistan', E'아시가바트\nAshgabat', 179),
        (E'투발루\nTuvalu', E'푸나푸티\nFunafuti', 180),
        (E'튀니지\nTunisia', E'튀니스\nTunis', 181),
        (E'트리니다드토바고\nTrinidad and Tobago', E'포트오브스페인\nPort of Spain', 182),
        (E'파나마\nPanama', E'파나마시티\nPanama City', 183),
        (E'파라과이\nParaguay', E'아순시온\nAsunción', 184),
        (E'파키스탄\nPakistan', E'이슬라마바드\nIslamabad', 185),
        (E'파푸아뉴기니\nPapua New Guinea', E'포트모르즈비\nPort Moresby', 186),
        (E'팔라우\nPalau', E'은게룰무드\nNgerulmud', 187),
        (E'페루\nPeru', E'리마\nLima', 188),
        (E'포르투갈\nPortugal', E'리스본\nLisbon', 189),
        (E'폴란드\nPoland', E'바르샤바\nWarsaw', 190),
        (E'프랑스\nFrance', E'파리\nParis', 191),
        (E'피지\nFiji', E'수바\nSuva', 192),
        (E'핀란드\nFinland', E'헬싱키\nHelsinki', 193),
        (E'필리핀\nPhilippines', E'마닐라\nManila', 194),
        (E'헝가리\nHungary', E'부다페스트\nBudapest', 195),
        (E'호주\nAustralia', E'캔버라\nCanberra', 196)
) AS v(front, back, ord)
WHERE d.name = '지리 · 세계 수도' AND d.source_type = 'BUILTIN';

INSERT INTO decks (name, owner_id, source_type, sort_order)
VALUES ('과학 · 원소 기호', NULL, 'BUILTIN', 80);

INSERT INTO cards (deck_id, front_text, back_text, sort_order)
SELECT d.id, v.front, v.back, v.ord
FROM decks d
CROSS JOIN (
    VALUES
        ('H', '수소 (1)', 1),
        ('He', '헬륨 (2)', 2),
        ('Li', '리튬 (3)', 3),
        ('Be', '베릴륨 (4)', 4),
        ('B', '붕소 (5)', 5),
        ('C', '탄소 (6)', 6),
        ('N', '질소 (7)', 7),
        ('O', '산소 (8)', 8),
        ('F', '플루오린 (9)', 9),
        ('Ne', '네온 (10)', 10),
        ('Na', '나트륨 (11)', 11),
        ('Mg', '마그네슘 (12)', 12),
        ('Al', '알루미늄 (13)', 13),
        ('Si', '규소 (14)', 14),
        ('P', '인 (15)', 15),
        ('S', '황 (16)', 16),
        ('Cl', '염소 (17)', 17),
        ('Ar', '아르곤 (18)', 18),
        ('K', '칼륨 (19)', 19),
        ('Ca', '칼슘 (20)', 20),
        ('Sc', '스칸듐 (21)', 21),
        ('Ti', '타이타늄 (22)', 22),
        ('V', '바나듐 (23)', 23),
        ('Cr', '크로뮴 (24)', 24),
        ('Mn', '망가니즈 (25)', 25),
        ('Fe', '철 (26)', 26),
        ('Co', '코발트 (27)', 27),
        ('Ni', '니켈 (28)', 28),
        ('Cu', '구리 (29)', 29),
        ('Zn', '아연 (30)', 30),
        ('Ga', '갈륨 (31)', 31),
        ('Ge', '저마늄 (32)', 32),
        ('As', '비소 (33)', 33),
        ('Se', '셀레늄 (34)', 34),
        ('Br', '브로민 (35)', 35),
        ('Kr', '크립톤 (36)', 36),
        ('Rb', '루비듐 (37)', 37),
        ('Sr', '스트론튬 (38)', 38),
        ('Y', '이트륨 (39)', 39),
        ('Zr', '지르코늄 (40)', 40),
        ('Nb', '나이오븀 (41)', 41),
        ('Mo', '몰리브데넘 (42)', 42),
        ('Tc', '테크네튬 (43)', 43),
        ('Ru', '루테늄 (44)', 44),
        ('Rh', '로듐 (45)', 45),
        ('Pd', '팔라듐 (46)', 46),
        ('Ag', '은 (47)', 47),
        ('Cd', '카드뮴 (48)', 48),
        ('In', '인듐 (49)', 49),
        ('Sn', '주석 (50)', 50),
        ('Sb', '안티모니 (51)', 51),
        ('Te', '텔루륨 (52)', 52),
        ('I', '아이오딘 (53)', 53),
        ('Xe', '제논 (54)', 54),
        ('Cs', '세슘 (55)', 55),
        ('Ba', '바륨 (56)', 56),
        ('La', '란타넘 (57)', 57),
        ('Ce', '세륨 (58)', 58),
        ('Pr', '프라세오디뮴 (59)', 59),
        ('Nd', '네오디뮴 (60)', 60),
        ('Pm', '프로메튬 (61)', 61),
        ('Sm', '사마륨 (62)', 62),
        ('Eu', '유로퓸 (63)', 63),
        ('Gd', '가돌리늄 (64)', 64),
        ('Tb', '터븀 (65)', 65),
        ('Dy', '디스프로슘 (66)', 66),
        ('Ho', '홀뮴 (67)', 67),
        ('Er', '어븀 (68)', 68),
        ('Tm', '툴륨 (69)', 69),
        ('Yb', '이터븀 (70)', 70),
        ('Lu', '루테튬 (71)', 71),
        ('Hf', '하프늄 (72)', 72),
        ('Ta', '탄탈럼 (73)', 73),
        ('W', '텅스텐 (74)', 74),
        ('Re', '레늄 (75)', 75),
        ('Os', '오스뮴 (76)', 76),
        ('Ir', '이리듐 (77)', 77),
        ('Pt', '백금 (78)', 78),
        ('Au', '금 (79)', 79),
        ('Hg', '수은 (80)', 80),
        ('Tl', '탈륨 (81)', 81),
        ('Pb', '납 (82)', 82),
        ('Bi', '비스무트 (83)', 83),
        ('Po', '폴로늄 (84)', 84),
        ('At', '아스타틴 (85)', 85),
        ('Rn', '라돈 (86)', 86),
        ('Fr', '프랑슘 (87)', 87),
        ('Ra', '라듐 (88)', 88),
        ('Ac', '악티늄 (89)', 89),
        ('Th', '토륨 (90)', 90),
        ('Pa', '프로트악티늄 (91)', 91),
        ('U', '우라늄 (92)', 92),
        ('Np', '넵투늄 (93)', 93),
        ('Pu', '플루토늄 (94)', 94),
        ('Am', '아메리슘 (95)', 95),
        ('Cm', '퀴륨 (96)', 96),
        ('Bk', '버클륨 (97)', 97),
        ('Cf', '캘리포늄 (98)', 98),
        ('Es', '아인슈타이늄 (99)', 99),
        ('Fm', '페르뮴 (100)', 100),
        ('Md', '멘델레븀 (101)', 101),
        ('No', '노벨륨 (102)', 102),
        ('Lr', '로렌슘 (103)', 103),
        ('Rf', '러더포듐 (104)', 104),
        ('Db', '더브늄 (105)', 105),
        ('Sg', '시보귬 (106)', 106),
        ('Bh', '보륨 (107)', 107),
        ('Hs', '하슘 (108)', 108),
        ('Mt', '마이트너륨 (109)', 109),
        ('Ds', '다름슈타튬 (110)', 110),
        ('Rg', '뢴트게늄 (111)', 111),
        ('Cn', '코페르니슘 (112)', 112),
        ('Nh', '니호늄 (113)', 113),
        ('Fl', '플레로븀 (114)', 114),
        ('Mc', '모스코븀 (115)', 115),
        ('Lv', '리버모륨 (116)', 116),
        ('Ts', '테네신 (117)', 117),
        ('Og', '오가네손 (118)', 118)
) AS v(front, back, ord)
WHERE d.name = '과학 · 원소 기호' AND d.source_type = 'BUILTIN';

INSERT INTO decks (name, owner_id, source_type, sort_order)
VALUES ('국어 · 사자성어', NULL, 'BUILTIN', 90);

INSERT INTO cards (deck_id, front_text, back_text, sort_order)
SELECT d.id, v.front, v.back, v.ord
FROM decks d
CROSS JOIN (
    VALUES
        (E'苛斂誅求\n가렴주구', '세금을 가혹하게 거두고 재물을 빼앗음', 1),
        (E'佳人薄命\n가인박명', '아름다운 사람은 운명이 기박함', 2),
        (E'刻骨難忘\n각골난망', '은혜를 뼈에 새겨 잊지 않음', 3),
        (E'刻舟求劍\n각주구검', '융통성 없이 낡은 생각만 고집함', 4),
        (E'各自圖生\n각자도생', '제각기 살길을 도모함', 5),
        (E'肝膽相照\n간담상조', '속마음을 터놓고 사귐', 6),
        (E'甘言利說\n감언이설', '달콤한 말과 이로운 이야기로 꾀임', 7),
        (E'甘呑苦吐\n감탄고토', '이로우면 삼키고 불리하면 뱉음', 8),
        (E'甲論乙駁\n갑론을박', '서로 의견을 내며 논쟁함', 9),
        (E'改過遷善\n개과천선', '잘못을 고치고 착하게 됨', 10),
        (E'去頭截尾\n거두절미', '앞뒤를 잘라 요점만 말함', 11),
        (E'擧案齊眉\n거안제미', '부부가 서로 공경함', 12),
        (E'見物生心\n견물생심', '물건을 보면 갖고 싶은 마음이 생김', 13),
        (E'犬猿之間\n견원지간', '사이가 매우 나쁨', 14),
        (E'結者解之\n결자해지', '매듭을 묶은 사람이 풀어야 함', 15),
        (E'輕擧妄動\n경거망동', '경솔하게 함부로 행동함', 16),
        (E'傾國之色\n경국지색', '나라를 기울게 할 만큼 아름다운 용모', 17),
        (E'驚天動地\n경천동지', '세상을 깜짝 놀라게 함', 18),
        (E'孤立無援\n고립무원', '외롭고 도와줄 사람이 없음', 19),
        (E'苦肉之計\n고육지계', '제 몸을 상하게 하여 적을 속이는 계책', 20),
        (E'苦盡甘來\n고진감래', '고생 끝에 즐거움이 옴', 21),
        (E'公明正大\n공명정대', '공평하고 밝고 올바름', 22),
        (E'過猶不及\n과유불급', '지나침은 모자람과 같음', 23),
        (E'刮目相對\n괄목상대', '다른 눈으로 상대를 봄. 크게 진보함', 24),
        (E'口蜜腹劍\n구밀복검', '말은 달콤하나 속에는 칼을 품음', 25),
        (E'九死一生\n구사일생', '죽을 고비를 넘기고 살아남', 26),
        (E'群鷄一鶴\n군계일학', '무리 가운데 뛰어난 사람', 27),
        (E'勸善懲惡\n권선징악', '선을 권하고 악을 징계함', 28),
        (E'捲土重來\n권토중래', '실패 뒤에 다시 일어남', 29),
        (E'極惡無道\n극악무도', '지극히 악하고 도리가 없음', 30),
        (E'近墨者黑\n근묵자흑', '먹을 가까이하면 검어진다', 31),
        (E'金科玉條\n금과옥조', '꼭 지켜야 할 소중한 법칙', 32),
        (E'錦上添花\n금상첨화', '좋은 일에 더 좋은 일이 겹침', 33),
        (E'起死回生\n기사회생', '거의 죽게 되었다가 다시 살아남', 34),
        (E'氣盡脈盡\n기진맥진', '기운과 맥이 다함', 35),
        (E'難攻不落\n난공불락', '공격하기 어렵고 함락되지 않음', 36),
        (E'難兄難弟\n난형난제', '우열을 가리기 어려움', 37),
        (E'南柯一夢\n남가일몽', '덧없이 지나간 한때의 영화', 38),
        (E'囊中之錐\n낭중지추', '재능이 저절로 드러남', 39),
        (E'內憂外患\n내우외환', '안팎의 근심과 걱정', 40),
        (E'勞心焦思\n노심초사', '마음을 쓰고 애를 태움', 41),
        (E'多岐亡羊\n다기망양', '방침이 많아 일을 그르침', 42),
        (E'多多益善\n다다익선', '많으면 많을수록 좋음', 43),
        (E'多事多難\n다사다난', '일이 많고 어려움이 많음', 44),
        (E'單刀直入\n단도직입', '바로 본론으로 들어감', 45),
        (E'斷金之交\n단금지교', '매우 굳은 우정', 46),
        (E'大器晩成\n대기만성', '큰 인물은 늦게 이루어짐', 47),
        (E'大同小異\n대동소이', '크게 같고 작게 다름', 48),
        (E'桃園結義\n도원결의', '뜻을 같이하여 형제가 되기로 맹세함', 49),
        (E'道聽途說\n도청도설', '길에서 듣고 길에서 말함. 근거 없는 소문', 50),
        (E'獨不將軍\n독불장군', '혼자 힘만으로는 어려움', 51),
        (E'同苦同樂\n동고동락', '괴로움과 즐거움을 함께함', 52),
        (E'東問西答\n동문서답', '물음과 상관없는 대답', 53),
        (E'同病相憐\n동병상련', '같은 처지끼리 서로 가엾게 여김', 54),
        (E'同床異夢\n동상이몽', '같은 자리에 있으면서 다른 생각을 함', 55),
        (E'東西古今\n동서고금', '동서양과 옛것과 지금. 모든 시대와 곳', 56),
        (E'東奔西走\n동분서주', '몹시 바쁘게 돌아다님', 57),
        (E'杜門不出\n두문불출', '문을 닫고 바깥출입을 하지 않음', 58),
        (E'燈下不明\n등하불명', '등잔 밑이 어두움. 가까운 일을 모름', 59),
        (E'馬耳東風\n마이동풍', '남의 말을 귀담아듣지 않음', 60),
        (E'莫上莫下\n막상막하', '우열을 가리기 어려움', 61),
        (E'明鏡止水\n명경지수', '맑은 거울과 고요한 물. 흔들림 없는 마음', 62),
        (E'名實相符\n명실상부', '이름과 실제가 서로 맞음', 63),
        (E'明若觀火\n명약관화', '불을 보듯 뻔함', 64),
        (E'武陵桃源\n무릉도원', '평화롭고 아름다운 이상향', 65),
        (E'無所不爲\n무소불위', '하지 못하는 일이 없음', 66),
        (E'無用之物\n무용지물', '쓸모없는 것', 67),
        (E'無爲徒食\n무위도식', '하는 일 없이 먹기만 함', 68),
        (E'門前成市\n문전성시', '찾아오는 사람이 많아 문 앞이 시장 같음', 69),
        (E'半信半疑\n반신반의', '반은 믿고 반은 의심함', 70),
        (E'百年河淸\n백년하청', '황하가 맑아지기를 백 년 기다림. 이루어지기 어려운 일', 71),
        (E'百發百中\n백발백중', '쏘는 족족 다 맞힘', 72),
        (E'伯牙絶絃\n백아절현', '자기를 알아주는 이가 없어 거문고 줄을 끊음', 73),
        (E'百折不屈\n백절불굴', '여러 번 꺾여도 굽히지 않음', 74),
        (E'伯仲之勢\n백중지세', '우열이 거의 같음', 75),
        (E'附和雷同\n부화뇌동', '줏대 없이 남의 의견에 따름', 76),
        (E'粉骨碎身\n분골쇄신', '온몸을 바쳐 힘씀', 77),
        (E'不恥下問\n불치하문', '아랫사람에게 묻는 것을 부끄러워하지 않음', 78),
        (E'髀肉之歎\n비육지탄', '재능을 쓰지 못해 한탄함', 79),
        (E'私利私慾\n사리사욕', '자기의 이익과 욕심만 꾀함', 80),
        (E'四面楚歌\n사면초가', '사방이 적으로 둘러싸여 고립됨', 81),
        (E'死生決斷\n사생결단', '죽기를 각오하고 결단함', 82),
        (E'事必歸正\n사필귀정', '일은 반드시 바른대로 돌아감', 83),
        (E'山戰水戰\n산전수전', '갖은 고생과 시련을 다 겪음', 84),
        (E'三顧草廬\n삼고초려', '인재를 얻기 위해 여러 번 찾아감', 85),
        (E'桑田碧海\n상전벽해', '뽕나무밭이 푸른 바다가 됨. 세상일이 많이 변함', 86),
        (E'塞翁之馬\n새옹지마', '인생의 길흉은 예측하기 어려움', 87),
        (E'先見之明\n선견지명', '앞일을 내다보는 지혜', 88),
        (E'先公後私\n선공후사', '공적인 일을 먼저 하고 사사로운 일은 뒤에 함', 89),
        (E'雪上加霜\n설상가상', '난처한 일에 또 난처한 일이 겹침', 90),
        (E'說往說來\n설왕설래', '서로 의견을 주고받음', 91),
        (E'小貪大失\n소탐대실', '작은 것을 탐하다 큰 것을 잃음', 92),
        (E'束手無策\n속수무책', '어찌할 도리가 없음', 93),
        (E'送舊迎新\n송구영신', '묵은해를 보내고 새해를 맞음', 94),
        (E'首丘初心\n수구초심', '근본을 잊지 않는 마음', 95),
        (E'袖手傍觀\n수수방관', '팔짱 끼고 곁에서 보기만 함', 96),
        (E'脣亡齒寒\n순망치한', '한쪽이 망하면 다른 쪽도 위태로움', 97),
        (E'十匙一飯\n십시일반', '여러 사람이 조금씩 도와 큰일을 이룸', 98),
        (E'我田引水\n아전인수', '자기에게만 유리하게 말함', 99),
        (E'安貧樂道\n안빈낙도', '가난한 가운데서도 도를 즐김', 100),
        (E'眼下無人\n안하무인', '눈 아래에 사람이 없음. 남을 업신여김', 101),
        (E'暗中摸索\n암중모색', '갈피를 잡지 못하고 더듬음', 102),
        (E'羊頭狗肉\n양두구육', '양머리를 걸어 놓고 개고기를 팖. 겉과 속이 다름', 103),
        (E'漁父之利\n어부지리', '둘이 다투는 사이 엉뚱한 사람이 이득을 봄', 104),
        (E'語不成說\n어불성설', '말이 조금도 이치에 닿지 않음', 105),
        (E'易地思之\n역지사지', '처지를 바꾸어 생각함', 106),
        (E'緣木求魚\n연목구어', '불가능한 일을 꾀함', 107),
        (E'寤寐不忘\n오매불망', '자나 깨나 잊지 못함', 108),
        (E'烏飛梨落\n오비이락', '까마귀 날자 배가 떨어짐. 우연히 겹쳐 의심받음', 109),
        (E'五里霧中\n오리무중', '앞이 보이지 않는 안개 속. 갈피를 잡을 수 없음', 110),
        (E'烏合之卒\n오합지졸', '규율 없이 모인 무리', 111),
        (E'溫故知新\n온고지신', '옛것을 익혀 새것을 앎', 112),
        (E'臥薪嘗膽\n와신상담', '원수를 갚으려고 온갖 어려움을 참고 견딤', 113),
        (E'外柔內剛\n외유내강', '겉은 부드러우나 속은 굳셈', 114),
        (E'愚公移山\n우공이산', '우공이 산을 옮김. 꾸준히 하면 이루어짐', 115),
        (E'愚問賢答\n우문현답', '어리석은 물음에 현명한 대답', 116),
        (E'迂餘曲折\n우여곡절', '여러 가지 복잡한 사정', 117),
        (E'右往左往\n우왕좌왕', '갈피를 못 잡고 이리저리 헤맴', 118),
        (E'雨後竹筍\n우후죽순', '비 온 뒤 죽순. 잇따라 많이 생김', 119),
        (E'有口無言\n유구무언', '입은 있으나 할 말이 없음', 120),
        (E'有名無實\n유명무실', '이름만 있고 실속이 없음', 121),
        (E'有備無患\n유비무환', '준비가 있으면 근심이 없음', 122),
        (E'類類相從\n유유상종', '같은 무리끼리 서로 모임', 123),
        (E'流言蜚語\n유언비어', '근거 없이 떠도는 말', 124),
        (E'有終之美\n유종지미', '끝까지 잘 마치는 아름다움', 125),
        (E'異口同聲\n이구동성', '여러 사람이 한목소리로 말함', 126),
        (E'以實直告\n이실직고', '사실 그대로 고함', 127),
        (E'以心傳心\n이심전심', '말없이 마음이 통함', 128),
        (E'以熱治熱\n이열치열', '강한 것을 강한 것으로 다스림', 129),
        (E'以夷制夷\n이이제이', '오랑캐로 오랑캐를 견제함', 130),
        (E'離合集散\n이합집산', '헤어졌다 모였다 함', 131),
        (E'因果應報\n인과응보', '원인에 따라 결과가 따름', 132),
        (E'一擧兩得\n일거양득', '한 가지 일로 두 가지 이익을 얻음', 133),
        (E'一擧一動\n일거일동', '하나의 거동과 동작. 모든 행동', 134),
        (E'一網打盡\n일망타진', '그물 한 번으로 모조리 잡음', 135),
        (E'一絲不亂\n일사불란', '조금도 흐트러짐이 없음', 136),
        (E'一瀉千里\n일사천리', '한 번에 천 리를 흘러감. 매우 빠름', 137),
        (E'一石二鳥\n일석이조', '돌 하나로 새 두 마리를 잡음', 138),
        (E'日就月將\n일취월장', '날로 달로 발전함', 139),
        (E'一片丹心\n일편단심', '변치 않는 한결같은 마음', 140),
        (E'臨機應變\n임기응변', '그때그때 형편에 맞게 대처함', 141),
        (E'自給自足\n자급자족', '제 힘으로 마련하여 씀', 142),
        (E'自問自答\n자문자답', '스스로 묻고 스스로 대답함', 143),
        (E'自繩自縛\n자승자박', '제 줄로 제 몸을 묶음. 제가 한 일에 제가 얽힘', 144),
        (E'自業自得\n자업자득', '자기가 한 일의 결과를 자기가 받음', 145),
        (E'自中之亂\n자중지란', '같은 편끼리 싸움', 146),
        (E'自畵自讚\n자화자찬', '제 그림을 제 입으로 칭찬함', 147),
        (E'賊反荷杖\n적반하장', '잘못한 쪽이 오히려 성냄', 148),
        (E'電光石火\n전광석화', '번개와 부싯돌 불. 매우 짧은 순간', 149),
        (E'前代未聞\n전대미문', '이전에는 들어 보지 못함', 150),
        (E'前無後無\n전무후무', '앞에도 뒤에도 없음. 아주 드묾', 151),
        (E'戰戰兢兢\n전전긍긍', '몹시 두려워 벌벌 띰', 152),
        (E'轉禍爲福\n전화위복', '화가 바뀌어 복이 됨', 153),
        (E'漸入佳境\n점입가경', '갈수록 재미있는 지경에 들어감', 154),
        (E'糟糠之妻\n조강지처', '가난한 시절을 함께 보낸 본처', 155),
        (E'朝令暮改\n조령모개', '명령이 자주 바뀜', 156),
        (E'朝變夕改\n조변석개', '아침저녁으로 변함. 변덕이 심함', 157),
        (E'朝三暮四\n조삼모사', '아침 세 개 저녁 네 개. 눈앞의 차이만 알고 실속은 같음', 158),
        (E'坐不安席\n좌불안석', '앉아도 자리가 편하지 않음. 초조함', 159),
        (E'竹馬故友\n죽마고우', '어릴 적부터 함께 놀던 벗', 160),
        (E'衆寡不敵\n중과부적', '적은 수로는 많은 수를 당하지 못함', 161),
        (E'衆口難防\n중구난방', '여러 사람의 말을 막기 어려움', 162),
        (E'重言復言\n중언부언', '같은 말을 되풀이함', 163),
        (E'知己之友\n지기지우', '속마음을 알아주는 벗', 164),
        (E'指鹿爲馬\n지록위마', '윗사람이 억지로 거짓을 통하게 함', 165),
        (E'至誠感天\n지성감천', '지극한 정성은 하늘도 감동함', 166),
        (E'知彼知己\n지피지기', '상대와 나를 앎', 167),
        (E'進退兩難\n진퇴양난', '나아가기도 물러서기도 어려움', 168),
        (E'千辛萬苦\n천신만고', '갖은 어려움과 고생', 169),
        (E'天衣無縫\n천의무봉', '하늘 옷에 솔기가 없음. 완전하여 흠이 없음', 170),
        (E'千載一遇\n천재일우', '좀처럼 오기 어려운 기회', 171),
        (E'天下太平\n천하태평', '온 세상이 평안함', 172),
        (E'靑出於藍\n청출어람', '제자가 스승보다 나음', 173),
        (E'焦眉之急\n초미지급', '눈썹에 불이 붙은 듯 매우 급함', 174),
        (E'七顚八起\n칠전팔기', '일곱 번 넘어져도 여덟 번 일어남', 175),
        (E'針小棒大\n침소봉대', '바늘을 막대처럼 부풀림. 과장함', 176),
        (E'他山之石\n타산지석', '다른 사람의 언행도 자기 수양에 도움이 됨', 177),
        (E'兎死狗烹\n토사구팽', '필요할 때만 이용하고 버림', 178),
        (E'表裏不同\n표리부동', '겉과 속이 다름', 179),
        (E'波瀾萬丈\n파란만장', '세상일이 매우 기구하고 변화가 많음', 180),
        (E'破邪顯正\n파사현정', '그릇된 것을 깨고 바른 것을 드러냄', 181),
        (E'破竹之勢\n파죽지세', '거침없이 나아가는 기세', 182),
        (E'風飛雹散\n풍비박산', '바람에 날리고 우박처럼 흩어짐. 산산이 부서짐', 183),
        (E'風前燈火\n풍전등화', '매우 위태로운 처지', 184),
        (E'鶴首苦待\n학수고대', '애타게 기다림', 185),
        (E'邯鄲之夢\n한단지몽', '한단의 꿈. 덧없는 한때의 영화', 186),
        (E'緘口無言\n함구무언', '입을 다물고 말하지 않음', 187),
        (E'咸興差使\n함흥차사', '심부름 가고 소식이 없음', 188),
        (E'虛無孟浪\n허무맹랑', '허황하고 실속이 없음', 189),
        (E'虛心坦懷\n허심탄회', '마음을 비우고 털어놓음', 190),
        (E'虛張聲勢\n허장성세', '실속 없이 허세를 부림', 191),
        (E'狐假虎威\n호가호위', '남의 권세를 빌려 위세를 부림', 192),
        (E'好事多魔\n호사다마', '좋은 일에는 흔히 탈이 많음', 193),
        (E'虎視眈眈\n호시탐탐', '호랑이처럼 노려보며 기회를 엿봄', 194),
        (E'豪言壯談\n호언장담', '호기 있게 크게 말함', 195),
        (E'渾然一體\n혼연일체', '완전히 하나가 됨', 196),
        (E'和氣靄靄\n화기애애', '분위기가 매우 화목함', 197),
        (E'畵龍點睛\n화룡점정', '용을 그리고 눈동자를 찍음. 가장 중요한 부분을 마침', 198),
        (E'換骨奪胎\n환골탈태', '뼈대를 바꿔 완전히 새롭게 됨', 199),
        (E'荒唐無稽\n황당무계', '허황하여 근거가 없음', 200),
        (E'橫說竪說\n횡설수설', '앞뒤 없이 말을 함부로 지껄임', 201),
        (E'後生可畏\n후생가외', '후배가 두렵도록 훌륭함', 202),
        (E'興亡盛衰\n흥망성쇠', '흥하고 망하고 성하고 쇠함', 203)
) AS v(front, back, ord)
WHERE d.name = '국어 · 사자성어' AND d.source_type = 'BUILTIN';


-- Merged from former V3: IT acronyms + English basics

INSERT INTO decks (name, owner_id, source_type, sort_order)
VALUES ('IT · 네트워크·보안 약어', NULL, 'BUILTIN', 100);

INSERT INTO cards (deck_id, front_text, back_text, sort_order)
SELECT d.id, v.front, v.back, v.ord
FROM decks d
CROSS JOIN (
    VALUES
        (E'HTTP', E'HyperText Transfer Protocol\n웹 문서 전송 프로토콜', 1),
        (E'HTTPS', E'HTTP Secure\nTLS로 암호화된 HTTP', 2),
        (E'HTML', E'HyperText Markup Language\n웹 페이지 마크업 언어', 3),
        (E'CSS', E'Cascading Style Sheets\n웹 스타일시트', 4),
        (E'JS', E'JavaScript\n웹 클라이언트 스크립트 언어', 5),
        (E'API', E'Application Programming Interface\n응용 프로그램 인터페이스', 6),
        (E'REST', E'Representational State Transfer\n자원 중심 HTTP API 스타일', 7),
        (E'SOAP', E'Simple Object Access Protocol\nXML 기반 웹 서비스 프로토콜', 8),
        (E'JSON', E'JavaScript Object Notation\n가벼운 데이터 교환 형식', 9),
        (E'XML', E'eXtensible Markup Language\n확장 가능한 마크업 언어', 10),
        (E'YAML', E'YAML Ain''t Markup Language\n설정용 데이터 직렬화 형식', 11),
        (E'URL', E'Uniform Resource Locator\n웹 자원 위치 주소', 12),
        (E'URI', E'Uniform Resource Identifier\n자원 식별자', 13),
        (E'URN', E'Uniform Resource Name\n위치와 무관한 자원 이름', 14),
        (E'DNS', E'Domain Name System\n도메인↔IP 변환 시스템', 15),
        (E'DHCP', E'Dynamic Host Configuration Protocol\nIP 자동 할당', 16),
        (E'IP', E'Internet Protocol\n패킷 라우팅 주소 체계', 17),
        (E'IPv4', E'Internet Protocol version 4\n32비트 IP 주소', 18),
        (E'IPv6', E'Internet Protocol version 6\n128비트 IP 주소', 19),
        (E'TCP', E'Transmission Control Protocol\n신뢰성 있는 전송 프로토콜', 20),
        (E'UDP', E'User Datagram Protocol\n비연결형 빠른 전송 프로토콜', 21),
        (E'ICMP', E'Internet Control Message Protocol\n네트워크 진단/오류 메시지', 22),
        (E'ARP', E'Address Resolution Protocol\nIP→MAC 주소 변환', 23),
        (E'NAT', E'Network Address Translation\n사설↔공인 IP 변환', 24),
        (E'VPN', E'Virtual Private Network\n가상 사설망', 25),
        (E'LAN', E'Local Area Network\n근거리 통신망', 26),
        (E'WAN', E'Wide Area Network\n광역 통신망', 27),
        (E'WLAN', E'Wireless LAN\n무선 근거리망', 28),
        (E'SSID', E'Service Set Identifier\n무선망 이름', 29),
        (E'MAC', E'Media Access Control\n네트워크 인터페이스 하드웨어 주소', 30),
        (E'OSI', E'Open Systems Interconnection\n7계층 네트워크 모델', 31),
        (E'TTL', E'Time To Live\n패킷/캐시 생존 시간', 32),
        (E'MTU', E'Maximum Transmission Unit\n최대 전송 단위', 33),
        (E'CDN', E'Content Delivery Network\n콘텐츠 분산 전송망', 34),
        (E'DNSSEC', E'DNS Security Extensions\nDNS 위변조 방지', 35),
        (E'DoH', E'DNS over HTTPS\nHTTPS로 DNS 질의', 36),
        (E'DoT', E'DNS over TLS\nTLS로 DNS 질의', 37),
        (E'SMTP', E'Simple Mail Transfer Protocol\n메일 전송 프로토콜', 38),
        (E'IMAP', E'Internet Message Access Protocol\n메일 서버 보관형 수신', 39),
        (E'POP3', E'Post Office Protocol v3\n메일 내려받기 프로토콜', 40),
        (E'FTP', E'File Transfer Protocol\n파일 전송 프로토콜', 41),
        (E'SFTP', E'SSH File Transfer Protocol\nSSH 기반 안전 파일 전송', 42),
        (E'SSH', E'Secure Shell\n원격 안전 접속 프로토콜', 43),
        (E'Telnet', E'Teletype Network\n암호화 없는 원격 접속', 44),
        (E'TLS', E'Transport Layer Security\n전송 계층 암호화', 45),
        (E'SSL', E'Secure Sockets Layer\nTLS 이전 암호화 프로토콜', 46),
        (E'PKI', E'Public Key Infrastructure\n공개키 기반 구조', 47),
        (E'CA', E'Certificate Authority\n인증서 발급 기관', 48),
        (E'CSR', E'Certificate Signing Request\n인증서 서명 요청', 49),
        (E'JWT', E'JSON Web Token\nJSON 기반 토큰 인증', 50),
        (E'OAuth', E'Open Authorization\n위임 인가 프레임워크', 51),
        (E'OIDC', E'OpenID Connect\nOAuth 위 신원 인증 계층', 52),
        (E'SSO', E'Single Sign-On\n단일 로그인', 53),
        (E'MFA', E'Multi-Factor Authentication\n다중 인증', 54),
        (E'2FA', E'Two-Factor Authentication\n2단계 인증', 55),
        (E'OTP', E'One-Time Password\n일회용 비밀번호', 56),
        (E'TOTP', E'Time-based OTP\n시간 기반 일회용 비밀번호', 57),
        (E'RBAC', E'Role-Based Access Control\n역할 기반 접근 제어', 58),
        (E'ACL', E'Access Control List\n접근 제어 목록', 59),
        (E'IAM', E'Identity and Access Management\n신원·접근 관리', 60),
        (E'XSS', E'Cross-Site Scripting\n사이트 간 스크립트 삽입 공격', 61),
        (E'CSRF', E'Cross-Site Request Forgery\n사이트 간 요청 위조', 62),
        (E'SQLi', E'SQL Injection\nSQL 삽입 공격', 63),
        (E'SSRF', E'Server-Side Request Forgery\n서버 측 요청 위조', 64),
        (E'RCE', E'Remote Code Execution\n원격 코드 실행', 65),
        (E'LFI', E'Local File Inclusion\n로컬 파일 포함 취약점', 66),
        (E'RFI', E'Remote File Inclusion\n원격 파일 포함 취약점', 67),
        (E'IDOR', E'Insecure Direct Object Reference\n불안전 직접 객체 참조', 68),
        (E'XXE', E'XML External Entity\nXML 외부 엔티티 공격', 69),
        (E'DoS', E'Denial of Service\n서비스 거부 공격', 70),
        (E'DDoS', E'Distributed DoS\n분산 서비스 거부 공격', 71),
        (E'MITM', E'Man-In-The-Middle\n중간자 공격', 72),
        (E'APT', E'Advanced Persistent Threat\n지능형 지속 위협', 73),
        (E'CVE', E'Common Vulnerabilities and Exposures\n공개 취약점 식별자', 74),
        (E'CVSS', E'Common Vulnerability Scoring System\n취약점 심각도 점수', 75),
        (E'CWE', E'Common Weakness Enumeration\n공통 약점 목록', 76),
        (E'OWASP', E'Open Worldwide Application Security Project\n웹 보안 커뮤니티/가이드', 77),
        (E'WAF', E'Web Application Firewall\n웹 애플리케이션 방화벽', 78),
        (E'IDS', E'Intrusion Detection System\n침입 탐지 시스템', 79),
        (E'IPS', E'Intrusion Prevention System\n침입 차단 시스템', 80),
        (E'SIEM', E'Security Information and Event Management\n보안 정보·이벤트 관리', 81),
        (E'SOC', E'Security Operations Center\n보안 관제 센터', 82),
        (E'EDR', E'Endpoint Detection and Response\n엔드포인트 탐지·대응', 83),
        (E'XDR', E'Extended Detection and Response\n확장 탐지·대응', 84),
        (E'DLP', E'Data Loss Prevention\n데이터 유출 방지', 85),
        (E'HSM', E'Hardware Security Module\n하드웨어 보안 모듈', 86),
        (E'AES', E'Advanced Encryption Standard\n대칭키 암호화 표준', 87),
        (E'RSA', E'Rivest-Shamir-Adleman\n공개키 암호 알고리즘', 88),
        (E'SHA', E'Secure Hash Algorithm\n안전한 해시 알고리즘 계열', 89),
        (E'HMAC', E'Hash-based Message Authentication Code\n해시 기반 메시지 인증', 90),
        (E'KMS', E'Key Management Service\n키 관리 서비스', 91),
        (E'Zero Trust', E'Zero Trust Security\n무조건 신뢰하지 않는 보안 모델', 92),
        (E'VLAN', E'Virtual LAN\n가상 근거리망', 93),
        (E'BGP', E'Border Gateway Protocol\n인터넷 경로 교환 프로토콜', 94),
        (E'OSPF', E'Open Shortest Path First\n링크 상태 라우팅 프로토콜', 95),
        (E'QoS', E'Quality of Service\n서비스 품질 제어', 96),
        (E'SDN', E'Software-Defined Networking\n소프트웨어 정의 네트워킹', 97),
        (E'NFC', E'Near Field Communication\n근거리 무선 통신', 98),
        (E'IoT', E'Internet of Things\n사물인터넷', 99),
        (E'MQTT', E'Message Queuing Telemetry Transport\n경량 IoT 메시징 프로토콜', 100),
        (E'gRPC', E'gRPC Remote Procedure Calls\n고성능 RPC 프레임워크', 101),
        (E'GraphQL', E'Graph Query Language\n클라이언트 정의형 API 질의', 102),
        (E'WebSocket', E'WebSocket\n양방향 실시간 웹 통신', 103),
        (E'CORS', E'Cross-Origin Resource Sharing\n교차 출처 리소스 공유', 104),
        (E'CSP', E'Content Security Policy\n콘텐츠 보안 정책', 105),
        (E'HSTS', E'HTTP Strict Transport Security\nHTTPS 강제 정책', 106),
        (E'SameSite', E'SameSite Cookie Attribute\n쿠키 전송 범위 제한', 107),
        (E'Cookie', E'HTTP Cookie\n브라우저에 저장되는 상태 데이터', 108),
        (E'Session', E'Session\n서버 측 사용자 상태 유지', 109),
        (E'CRUD', E'Create Read Update Delete\n기본 데이터 조작 연산', 110),
        (E'ORM', E'Object-Relational Mapping\n객체-관계 매핑', 111),
        (E'SQL', E'Structured Query Language\n관계형 DB 질의 언어', 112),
        (E'NoSQL', E'Not Only SQL\n비관계형 DB 계열', 113),
        (E'ACID', E'Atomicity Consistency Isolation Durability\n트랜잭션 신뢰성 속성', 114),
        (E'BASE', E'Basically Available Soft state Eventual consistency\n분산계 가용성 중심 모델', 115),
        (E'CAP', E'Consistency Availability Partition tolerance\n분산 시스템 트레이드오프', 116),
        (E'ETL', E'Extract Transform Load\n데이터 추출·변환·적재', 117),
        (E'CI', E'Continuous Integration\n지속적 통합', 118),
        (E'CD', E'Continuous Delivery/Deployment\n지속적 전달/배포', 119),
        (E'IaC', E'Infrastructure as Code\n코드로 인프라 관리', 120),
        (E'VM', E'Virtual Machine\n가상 머신', 121),
        (E'Container', E'Container\n격리된 실행 환경 단위', 122),
        (E'K8s', E'Kubernetes\n컨테이너 오케스트레이션', 123),
        (E'Docker', E'Docker\n컨테이너 런타임/플랫폼', 124),
        (E'Serverless', E'Serverless Computing\n서버 관리 없이 함수 실행', 125),
        (E'SaaS', E'Software as a Service\n서비스형 소프트웨어', 126),
        (E'PaaS', E'Platform as a Service\n서비스형 플랫폼', 127),
        (E'IaaS', E'Infrastructure as a Service\n서비스형 인프라', 128),
        (E'SLA', E'Service Level Agreement\n서비스 수준 협약', 129),
        (E'SLO', E'Service Level Objective\n서비스 수준 목표', 130),
        (E'SLI', E'Service Level Indicator\n서비스 수준 지표', 131),
        (E'RTO', E'Recovery Time Objective\n복구 목표 시간', 132),
        (E'RPO', E'Recovery Point Objective\n복구 목표 시점', 133),
        (E'BCP', E'Business Continuity Plan\n업무 연속성 계획', 134),
        (E'DR', E'Disaster Recovery\n재해 복구', 135),
        (E'Log4Shell', E'Log4j / Log4Shell\n유명 Java 로깅 취약점 사례', 136),
        (E'Zero-day', E'Zero-day Vulnerability\n패치 전 공개/악용 취약점', 137),
        (E'Phishing', E'Phishing\n사칭으로 정보 탈취하는 사회공학 공격', 138),
        (E'Ransomware', E'Ransomware\n암호화 후 금전 요구 악성코드', 139),
        (E'Malware', E'Malicious Software\n악성 소프트웨어 통칭', 140),
        (E'Spyware', E'Spyware\n몰래 정보 수집하는 악성코드', 141),
        (E'Trojan', E'Trojan Horse\n위장해 침투하는 악성코드', 142),
        (E'Botnet', E'Botnet\n감염 PC로 구성한 좀비망', 143),
        (E'Firewall', E'Firewall\n네트워크 출입 통제 장치/SW', 144),
        (E'Proxy', E'Proxy Server\n중계 서버', 145),
        (E'Reverse Proxy', E'Reverse Proxy\n서버 앞단 중계/부하분산', 146),
        (E'Load Balancer', E'Load Balancer\n부하 분산 장치', 147),
        (E'Rate Limit', E'Rate Limiting\n요청 횟수 제한', 148),
        (E'Throttle', E'Throttling\n처리량 억제', 149),
        (E'Cache', E'Cache\n빠른 재사용을 위한 임시 저장', 150),
        (E'CDN Edge', E'CDN Edge\n사용자 가까운 캐시 노드', 151),
        (E'Blue/Green', E'Blue-Green Deployment\n두 환경 전환형 배포', 152),
        (E'Canary', E'Canary Release\n소량 트래픽으로 점진 배포', 153),
        (E'A/B Test', E'A/B Testing\n버전 비교 실험', 154),
        (E'Observability', E'Observability\n로그·메트릭·트레이스로 상태 파악', 155),
        (E'Tracing', E'Distributed Tracing\n분산 요청 경로 추적', 156),
        (E'Metric', E'Metric\n수치형 관측 지표', 157),
        (E'Log', E'Log\n이벤트 기록', 158),
        (E'Alert', E'Alert\n이상 징후 알림', 159),
        (E'Incident', E'Incident\n서비스 장애/보안 사고', 160),
        (E'Patch', E'Patch\n취약점·버그 수정 배포', 161),
        (E'Hardening', E'Hardening\n보안 강화 설정', 162),
        (E'Least Privilege', E'Principle of Least Privilege\n최소 권한 원칙', 163),
        (E'Defense in Depth', E'Defense in Depth\n다층 방어', 164),
        (E'Salt', E'Password Salt\n해시 전에 넣는 난수 값', 165),
        (E'Pepper', E'Password Pepper\n서버 비밀로 추가하는 값', 166),
        (E'Bcrypt', E'bcrypt\n비밀번호 해시 알고리즘', 167),
        (E'Argon2', E'Argon2\n현대적 비밀번호 해시 알고리즘', 168),
        (E'Nmap', E'Network Mapper\n포트/호스트 스캔 도구', 169),
        (E'Wireshark', E'Wireshark\n패킷 분석 도구', 170),
        (E'Burp', E'Burp Suite\n웹 보안 테스트 도구', 171),
        (E'Metasploit', E'Metasploit\n침투 테스트 프레임워크', 172),
        (E'SOC 2', E'SOC 2\n보안·가용성 등 준수 보고서 체계', 173),
        (E'GDPR', E'General Data Protection Regulation\nEU 개인정보 보호 규정', 174),
        (E'PII', E'Personally Identifiable Information\n개인 식별 정보', 175),
        (E'PCI DSS', E'Payment Card Industry Data Security Standard\n카드결제 보안 표준', 176),
        (E'ISO 27001', E'ISO/IEC 27001\n정보보호 경영시스템 국제표준', 177),
        (E'NIST', E'National Institute of Standards and Technology\n미국 표준·보안 가이드 기관', 178),
        (E'MITRE ATT&CK', E'MITRE ATT&CK\n공격 전술·기법 지식베이스', 179),
        (E'LDAP', E'Lightweight Directory Access Protocol\n디렉터리 조회 프로토콜', 180),
        (E'Kerberos', E'Kerberos\n티켓 기반 네트워크 인증 프로토콜', 181),
        (E'SAML', E'Security Assertion Markup Language\nSSO용 XML 인증/인가 표준', 182),
        (E'RADIUS', E'Remote Authentication Dial-In User Service\n원격 인증 프로토콜', 183),
        (E'NTP', E'Network Time Protocol\n시간 동기화 프로토콜', 184),
        (E'SNMP', E'Simple Network Management Protocol\n네트워크 장비 관리 프로토콜', 185),
        (E'HTTP/2', E'HTTP/2\n멀티플렉싱 등 성능 개선 HTTP', 186),
        (E'HTTP/3', E'HTTP/3\nQUIC 기반 최신 HTTP', 187),
        (E'QUIC', E'Quick UDP Internet Connections\nUDP 기반 전송 프로토콜', 188),
        (E'mTLS', E'Mutual TLS\n양방향 인증서 인증', 189),
        (E'SPA', E'Single Page Application\n단일 페이지 웹 앱', 190),
        (E'SSR', E'Server-Side Rendering\n서버에서 HTML 렌더링', 191),
        (E'CSR (Render)', E'Client-Side Rendering\n브라우저에서 렌더링', 192),
        (E'CDN PoP', E'Point of Presence\nCDN 접속 지점', 193),
        (E'AZ', E'Availability Zone\n클라우드 가용 영역', 194),
        (E'HA', E'High Availability\n고가용성', 195),
        (E'FT', E'Fault Tolerance\n장애 허용', 196),
        (E'RAID', E'Redundant Array of Independent Disks\n디스크 이중화 구성', 197),
        (E'SAN', E'Storage Area Network\n스토리지 전용망', 198),
        (E'NAS', E'Network Attached Storage\n네트워크 연결 저장장치', 199),
        (E'BIOS', E'Basic Input/Output System\n펌웨어 기본 입출력', 200),
        (E'UEFI', E'Unified Extensible Firmware Interface\n현대적 PC 펌웨어', 201),
        (E'CPU', E'Central Processing Unit\n중앙처리장치', 202),
        (E'GPU', E'Graphics Processing Unit\n그래픽/병렬 연산 장치', 203),
        (E'RAM', E'Random Access Memory\n주기억장치', 204),
        (E'SSD', E'Solid State Drive\n반도체 저장장치', 205),
        (E'HDD', E'Hard Disk Drive\n자기 디스크 저장장치', 206),
        (E'OS', E'Operating System\n운영체제', 207),
        (E'CLI', E'Command Line Interface\n명령줄 인터페이스', 208),
        (E'GUI', E'Graphical User Interface\n그래픽 사용자 인터페이스', 209),
        (E'SDK', E'Software Development Kit\n개발 도구 모음', 210),
        (E'IDE', E'Integrated Development Environment\n통합 개발 환경', 211),
        (E'VCS', E'Version Control System\n버전 관리 시스템', 212),
        (E'Git', E'Git\n분산 버전 관리 시스템', 213),
        (E'PR', E'Pull Request\n코드 병합 요청', 214),
        (E'MR', E'Merge Request\n코드 병합 요청(GitLab)', 215),
        (E'QA', E'Quality Assurance\n품질 보증', 216),
        (E'UAT', E'User Acceptance Testing\n사용자 인수 테스트', 217),
        (E'MVP', E'Minimum Viable Product\n최소 기능 제품', 218),
        (E'POC', E'Proof of Concept\n개념 검증', 219),
        (E'RFI (Biz)', E'Request for Information\n정보 요청서', 220),
        (E'RFP', E'Request for Proposal\n제안 요청서', 221)
) AS v(front, back, ord)
WHERE d.name = 'IT · 네트워크·보안 약어' AND d.source_type = 'BUILTIN';

INSERT INTO decks (name, owner_id, source_type, sort_order)
VALUES ('영어 · 기초 동사', NULL, 'BUILTIN', 110);

INSERT INTO cards (deck_id, front_text, back_text, sort_order)
SELECT d.id, v.front, v.back, v.ord
FROM decks d
CROSS JOIN (
    VALUES
        ('be', '이다 / 있다', 1),
        ('have', '가지다', 2),
        ('do', '하다', 3),
        ('say', '말하다', 4),
        ('go', '가다', 5),
        ('get', '얻다 / 받다', 6),
        ('make', '만들다', 7),
        ('know', '알다', 8),
        ('think', '생각하다', 9),
        ('take', '가져가다 / 받다', 10),
        ('see', '보다', 11),
        ('come', '오다', 12),
        ('want', '원하다', 13),
        ('look', '바라보다 / ~처럼 보이다', 14),
        ('use', '사용하다', 15),
        ('find', '찾다', 16),
        ('give', '주다', 17),
        ('tell', '말해주다', 18),
        ('work', '일하다 / 작동하다', 19),
        ('call', '부르다 / 전화하다', 20),
        ('try', '시도하다', 21),
        ('ask', '묻다 / 요청하다', 22),
        ('need', '필요하다', 23),
        ('feel', '느끼다', 24),
        ('become', '되다', 25),
        ('leave', '떠나다 / 남겨두다', 26),
        ('put', '놓다', 27),
        ('mean', '의미하다', 28),
        ('keep', '계속하다 / 유지하다', 29),
        ('let', '~하게 하다', 30),
        ('begin', '시작하다', 31),
        ('seem', '~인 것 같다', 32),
        ('help', '돕다', 33),
        ('talk', '이야기하다', 34),
        ('turn', '돌다 / 바꾸다', 35),
        ('start', '시작하다', 36),
        ('show', '보여주다', 37),
        ('hear', '듣다', 38),
        ('play', '놀다 / 연주하다', 39),
        ('run', '달리다 / 운영하다', 40),
        ('move', '움직이다', 41),
        ('like', '좋아하다', 42),
        ('live', '살다', 43),
        ('believe', '믿다', 44),
        ('hold', '잡다 / 개최하다', 45),
        ('bring', '가져오다', 46),
        ('happen', '일어나다', 47),
        ('write', '쓰다', 48),
        ('provide', '제공하다', 49),
        ('sit', '앉다', 50),
        ('stand', '서다', 51),
        ('lose', '잃다 / 지다', 52),
        ('pay', '지불하다', 53),
        ('meet', '만나다', 54),
        ('include', '포함하다', 55),
        ('continue', '계속하다', 56),
        ('set', '놓다 / 설정하다', 57),
        ('learn', '배우다', 58),
        ('change', '바꾸다', 59),
        ('lead', '이끌다', 60),
        ('understand', '이해하다', 61),
        ('watch', '지켜보다', 62),
        ('follow', '따르다', 63),
        ('stop', '멈추다', 64),
        ('create', '창조하다 / 만들다', 65),
        ('speak', '말하다', 66),
        ('read', '읽다', 67),
        ('allow', '허용하다', 68),
        ('add', '더하다', 69),
        ('spend', '쓰다 / 보내다', 70),
        ('grow', '성장하다', 71),
        ('open', '열다', 72),
        ('walk', '걷다', 73),
        ('win', '이기다', 74),
        ('offer', '제안하다', 75),
        ('remember', '기억하다', 76),
        ('love', '사랑하다', 77),
        ('consider', '고려하다', 78),
        ('appear', '나타나다', 79),
        ('buy', '사다', 80),
        ('wait', '기다리다', 81),
        ('serve', '섬기다 / 제공하다', 82),
        ('die', '죽다', 83),
        ('send', '보내다', 84),
        ('expect', '기대하다', 85),
        ('build', '짓다', 86),
        ('stay', '머무르다', 87),
        ('fall', '떨어지다', 88),
        ('cut', '자르다', 89),
        ('reach', '도달하다', 90),
        ('kill', '죽이다', 91),
        ('remain', '남다', 92),
        ('suggest', '제안하다', 93),
        ('raise', '올리다 / 기르다', 94),
        ('pass', '지나가다 / 통과하다', 95),
        ('sell', '팔다', 96),
        ('require', '요구하다', 97),
        ('report', '보고하다', 98),
        ('decide', '결정하다', 99),
        ('pull', '끌다', 100),
        ('return', '돌아가다 / 반환하다', 101),
        ('explain', '설명하다', 102),
        ('hope', '희망하다', 103),
        ('develop', '개발하다', 104),
        ('carry', '나르다', 105),
        ('break', '깨다 / 부수다', 106),
        ('receive', '받다', 107),
        ('agree', '동의하다', 108),
        ('support', '지지하다', 109),
        ('hit', '치다', 110),
        ('produce', '생산하다', 111),
        ('eat', '먹다', 112),
        ('cover', '덮다 / 다루다', 113),
        ('catch', '잡다', 114),
        ('draw', '그리다 / 끌다', 115),
        ('choose', '고르다', 116),
        ('cause', '일으키다', 117),
        ('point', '가리키다', 118),
        ('listen', '귀를 기울이다', 119),
        ('realize', '깨닫다', 120),
        ('place', '두다', 121),
        ('protect', '보호하다', 122),
        ('rise', '오르다', 123),
        ('accept', '받아들이다', 124),
        ('refuse', '거절하다', 125),
        ('improve', '개선하다', 126),
        ('avoid', '피하다', 127),
        ('enjoy', '즐기다', 128),
        ('prepare', '준비하다', 129),
        ('compare', '비교하다', 130),
        ('prefer', '선호하다', 131),
        ('describe', '묘사하다', 132),
        ('finish', '끝내다', 133),
        ('forget', '잊다', 134),
        ('notice', '알아차리다', 135),
        ('share', '공유하다', 136),
        ('apply', '적용하다 / 지원하다', 137),
        ('depend', '의존하다', 138),
        ('exist', '존재하다', 139),
        ('reduce', '줄이다', 140),
        ('increase', '늘리다', 141),
        ('mention', '언급하다', 142),
        ('achieve', '달성하다', 143),
        ('manage', '관리하다', 144),
        ('focus', '집중하다', 145),
        ('check', '확인하다', 146),
        ('join', '합류하다', 147),
        ('save', '구하다 / 저장하다', 148),
        ('solve', '해결하다', 149),
        ('fail', '실패하다', 150),
        ('succeed', '성공하다', 151),
        ('argue', '논쟁하다', 152),
        ('complain', '불평하다', 153),
        ('encourage', '격려하다', 154),
        ('prevent', '막다', 155),
        ('recognize', '알아보다 / 인정하다', 156),
        ('replace', '교체하다', 157),
        ('search', '검색하다', 158),
        ('select', '선택하다', 159),
        ('study', '공부하다', 160),
        ('teach', '가르치다', 161),
        ('travel', '여행하다', 162),
        ('visit', '방문하다', 163),
        ('wear', '입다', 164),
        ('worry', '걱정하다', 165),
        ('attend', '참석하다', 166),
        ('belong', '속하다', 167),
        ('borrow', '빌리다', 168),
        ('collect', '모으다', 169),
        ('confirm', '확인하다', 170),
        ('deliver', '배달하다', 171),
        ('discover', '발견하다', 172),
        ('discuss', '토론하다', 173),
        ('divide', '나누다', 174),
        ('examine', '조사하다', 175),
        ('express', '표현하다', 176),
        ('form', '형성하다', 177),
        ('gain', '얻다', 178),
        ('handle', '다루다', 179),
        ('ignore', '무시하다', 180),
        ('imagine', '상상하다', 181),
        ('invite', '초대하다', 182),
        ('maintain', '유지하다', 183),
        ('measure', '측정하다', 184),
        ('miss', '놓치다 / 그리워하다', 185),
        ('obtain', '획득하다', 186),
        ('occur', '발생하다', 187),
        ('organize', '조직하다', 188),
        ('perform', '수행하다 / 공연하다', 189),
        ('permit', '허락하다', 190),
        ('predict', '예측하다', 191),
        ('prove', '증명하다', 192),
        ('publish', '출판하다', 193),
        ('react', '반응하다', 194),
        ('reflect', '반영하다 / 숙고하다', 195),
        ('relate', '관련시키다', 196),
        ('rely', '의지하다', 197),
        ('remove', '제거하다', 198),
        ('reply', '답하다', 199),
        ('represent', '대표하다', 200),
        ('request', '요청하다', 201),
        ('respond', '응답하다', 202),
        ('reveal', '드러내다', 203),
        ('review', '검토하다', 204),
        ('risk', '위험을 무릅쓰다', 205),
        ('satisfy', '만족시키다', 206),
        ('seek', '찾다', 207),
        ('separate', '분리하다', 208),
        ('settle', '해결하다 / 정착하다', 209),
        ('shut', '닫다', 210),
        ('sign', '서명하다', 211),
        ('suffer', '겪다 / 고통받다', 212),
        ('supply', '공급하다', 213),
        ('survive', '생존하다', 214),
        ('threaten', '위협하다', 215),
        ('throw', '던지다', 216),
        ('touch', '만지다', 217),
        ('train', '훈련하다', 218),
        ('treat', '대하다 / 치료하다', 219),
        ('trust', '신뢰하다', 220),
        ('vary', '달라지다', 221),
        ('warn', '경고하다', 222),
        ('waste', '낭비하다', 223),
        ('wonder', '궁금해하다', 224),
        ('admit', '인정하다', 225),
        ('advise', '조언하다', 226),
        ('afford', '여유가 되다', 227),
        ('announce', '발표하다', 228),
        ('apologize', '사과하다', 229),
        ('arrange', '정리하다 / 마련하다', 230),
        ('assume', '가정하다', 231),
        ('attach', '붙이다', 232),
        ('attack', '공격하다', 233),
        ('attempt', '시도하다', 234),
        ('attract', '끌다', 235),
        ('balance', '균형을 맞추다', 236),
        ('ban', '금지하다', 237),
        ('base', '기초를 두다', 238),
        ('beat', '때리다 / 이기다', 239),
        ('behave', '행동하다', 240),
        ('bend', '구부리다', 241),
        ('benefit', '이익을 주다', 242),
        ('bet', '내기를 하다', 243),
        ('blame', '비난하다', 244),
        ('blow', '불다', 245),
        ('boil', '끓이다', 246),
        ('bother', '귀찮게 하다', 247),
        ('burn', '태우다 / 타다', 248),
        ('calculate', '계산하다', 249),
        ('cancel', '취소하다', 250),
        ('care', '신경 쓰다', 251),
        ('celebrate', '축하하다', 252),
        ('challenge', '도전하다', 253),
        ('charge', '청구하다 / 충전하다', 254),
        ('chase', '쫓다', 255),
        ('cheer', '응원하다', 256),
        ('chew', '씹다', 257),
        ('claim', '주장하다', 258),
        ('climb', '오르다', 259),
        ('combine', '결합하다', 260),
        ('communicate', '의사소통하다', 261),
        ('compete', '경쟁하다', 262),
        ('concentrate', '집중하다', 263),
        ('concern', '걱정하다 / 관련되다', 264),
        ('conclude', '결론짓다', 265),
        ('conduct', '수행하다', 266),
        ('confess', '고백하다', 267),
        ('confuse', '혼란스럽게 하다', 268),
        ('connect', '연결하다', 269),
        ('consist', '~로 구성되다', 270),
        ('consume', '소비하다', 271),
        ('contain', '포함하다', 272),
        ('contribute', '기여하다', 273),
        ('control', '통제하다', 274),
        ('convince', '설득하다', 275),
        ('cook', '요리하다', 276),
        ('copy', '복사하다', 277),
        ('correct', '고치다', 278),
        ('count', '세다', 279),
        ('crash', '충돌하다 / 다운되다', 280),
        ('cross', '건너다', 281),
        ('cry', '울다', 282),
        ('damage', '손상시키다', 283),
        ('dance', '춤추다', 284),
        ('deal', '다루다 / 거래하다', 285),
        ('delay', '지연시키다', 286),
        ('demand', '요구하다', 287),
        ('deny', '부인하다', 288),
        ('deserve', '받을 자격이 있다', 289),
        ('design', '설계하다', 290),
        ('destroy', '파괴하다', 291),
        ('determine', '결정하다 / 밝히다', 292),
        ('differ', '다르다', 293),
        ('dig', '파다', 294),
        ('disagree', '동의하지 않다', 295),
        ('disappear', '사라지다', 296),
        ('dislike', '싫어하다', 297),
        ('distribute', '배포하다', 298),
        ('doubt', '의심하다', 299),
        ('drag', '끌다', 300),
        ('dream', '꿈꾸다', 301),
        ('dress', '옷을 입다', 302),
        ('drink', '마시다', 303),
        ('drive', '운전하다', 304),
        ('drop', '떨어뜨리다', 305),
        ('dry', '말리다', 306),
        ('earn', '벌다', 307),
        ('educate', '교육하다', 308),
        ('elect', '선출하다', 309),
        ('embarrass', '당황하게 하다', 310),
        ('emerge', '나타나다', 311),
        ('employ', '고용하다', 312),
        ('enable', '가능하게 하다', 313),
        ('end', '끝내다', 314),
        ('engage', '관여하다', 315),
        ('enhance', '향상시키다', 316),
        ('ensure', '보장하다', 317),
        ('enter', '들어가다', 318),
        ('entertain', '즐겁게 하다', 319),
        ('escape', '탈출하다', 320),
        ('establish', '설립하다', 321),
        ('estimate', '추정하다', 322),
        ('evaluate', '평가하다', 323),
        ('exchange', '교환하다', 324),
        ('exclude', '제외하다', 325),
        ('expand', '확장하다', 326),
        ('experience', '경험하다', 327),
        ('experiment', '실험하다', 328),
        ('explode', '폭발하다', 329),
        ('explore', '탐험하다', 330),
        ('export', '수출하다', 331),
        ('extend', '연장하다', 332),
        ('face', '직면하다', 333),
        ('fade', '희미해지다', 334),
        ('feed', '먹이를 주다', 335),
        ('fight', '싸우다', 336),
        ('fill', '채우다', 337),
        ('film', '촬영하다', 338),
        ('fix', '형성하다', 339),
        ('fit', '맞다', 340),
        ('flee', '도망치다', 341),
        ('float', '뜨다', 342),
        ('flow', '흐르다', 343),
        ('fly', '날다', 344),
        ('fold', '접다', 345),
        ('force', '강요하다', 346),
        ('forgive', '용서하다', 347),
        ('found', '설립하다', 348),
        ('freeze', '얼리다', 349),
        ('frighten', '무섭게 하다', 350),
        ('fry', '튀기다', 351)
) AS v(front, back, ord)
WHERE d.name = '영어 · 기초 동사' AND d.source_type = 'BUILTIN';

INSERT INTO decks (name, owner_id, source_type, sort_order)
VALUES ('영어 · 기초 형용사', NULL, 'BUILTIN', 120);

INSERT INTO cards (deck_id, front_text, back_text, sort_order)
SELECT d.id, v.front, v.back, v.ord
FROM decks d
CROSS JOIN (
    VALUES
        ('good', '좋은', 1),
        ('new', '새로운', 2),
        ('first', '첫 번째의', 3),
        ('last', '마지막의', 4),
        ('long', '긴', 5),
        ('great', '훌륭한 / 큰', 6),
        ('little', '작은 / 조금의', 7),
        ('own', '자신의', 8),
        ('other', '다른', 9),
        ('old', '오래된 / 나이 든', 10),
        ('right', '옳은 / 오른쪽의', 11),
        ('big', '큰', 12),
        ('high', '높은', 13),
        ('different', '다른', 14),
        ('small', '작은', 15),
        ('large', '큰', 16),
        ('next', '다음의', 17),
        ('early', '이른', 18),
        ('young', '젊은', 19),
        ('important', '중요한', 20),
        ('few', '적은 수의', 21),
        ('public', '공공의', 22),
        ('bad', '나쁜', 23),
        ('same', '같은', 24),
        ('able', '~할 수 있는', 25),
        ('human', '인간의', 26),
        ('local', '지역의', 27),
        ('sure', '확실한', 28),
        ('best', '최고의', 29),
        ('better', '더 나은', 30),
        ('low', '낮은', 31),
        ('hard', '어려운 / 단단한', 32),
        ('major', '주요한', 33),
        ('economic', '경제의', 34),
        ('strong', '강한', 35),
        ('possible', '가능한', 36),
        ('whole', '전체의', 37),
        ('free', '무료의 / 자유로운', 38),
        ('military', '군대의', 39),
        ('true', '진실한', 40),
        ('federal', '연방의', 41),
        ('international', '국제적인', 42),
        ('full', '가득 찬', 43),
        ('special', '특별한', 44),
        ('easy', '쉬운', 45),
        ('clear', '분명한', 46),
        ('recent', '최근의', 47),
        ('certain', '어떤 / 확실한', 48),
        ('personal', '개인의', 49),
        ('open', '열린', 50),
        ('red', '빨간', 51),
        ('difficult', '어려운', 52),
        ('available', '이용 가능한', 53),
        ('likely', '~할 것 같은', 54),
        ('short', '짧은', 55),
        ('single', '하나의 / 싱글의', 56),
        ('medical', '의학의', 57),
        ('current', '현재의', 58),
        ('wrong', '잘못된', 59),
        ('private', '사설의 / 개인의', 60),
        ('past', '과거의', 61),
        ('foreign', '외국의', 62),
        ('fine', '좋은 / 괜찮은', 63),
        ('common', '흔한 / 공통의', 64),
        ('poor', '가난한 / 형편없는', 65),
        ('natural', '자연의', 66),
        ('significant', '중요한 / 상당한', 67),
        ('similar', '비슷한', 68),
        ('hot', '뜨거운', 69),
        ('dead', '죽은', 70),
        ('central', '중심의', 71),
        ('happy', '행복한', 72),
        ('serious', '심각한 / 진지한', 73),
        ('ready', '준비가 된', 74),
        ('simple', '간단한', 75),
        ('left', '왼쪽의 / 남은', 76),
        ('physical', '신체적 / 물리적', 77),
        ('general', '일반적인', 78),
        ('environmental', '환경의', 79),
        ('financial', '재정의', 80),
        ('blue', '파란', 81),
        ('democratic', '민주적인', 82),
        ('dark', '어두운', 83),
        ('various', '다양한', 84),
        ('entire', '전체의', 85),
        ('close', '가까운', 86),
        ('legal', '법적인', 87),
        ('religious', '종교적인', 88),
        ('cold', '추운', 89),
        ('final', '최종의', 90),
        ('main', '주요한', 91),
        ('green', '초록의', 92),
        ('nice', '멋진 / 친절한', 93),
        ('huge', '거대한', 94),
        ('popular', '인기 있는', 95),
        ('traditional', '전통적인', 96),
        ('cultural', '문화의', 97),
        ('necessary', '필요한', 98),
        ('safe', '안전한', 99),
        ('successful', '성공적인', 100),
        ('beautiful', '아름다운', 101),
        ('interesting', '흥미로운', 102),
        ('useful', '유용한', 103),
        ('expensive', '비싼', 104),
        ('cheap', '저렴한', 105),
        ('fast', '빠른', 106),
        ('slow', '느린', 107),
        ('quiet', '조용한', 108),
        ('noisy', '시끄러운', 109),
        ('clean', '깨끗한', 110),
        ('dirty', '더러운', 111),
        ('busy', '바쁜', 112),
        ('empty', '빈', 113),
        ('heavy', '무거운', 114),
        ('light', '가벼운 / 밝은', 115),
        ('soft', '부드러운', 116),
        ('warm', '따뜻한', 117),
        ('cool', '시원한 / 멋진', 118),
        ('dry', '건조한', 119),
        ('wet', '젖은', 120),
        ('fresh', '신선한', 121),
        ('modern', '현대적인', 122),
        ('ancient', '고대의', 123),
        ('famous', '유명한', 124),
        ('unknown', '알려지지 않은', 125),
        ('friendly', '친절한', 126),
        ('angry', '화난', 127),
        ('afraid', '두려워하는', 128),
        ('lonely', '외로운', 129),
        ('tired', '피곤한', 130),
        ('hungry', '배고픈', 131),
        ('thirsty', '목마른', 132),
        ('healthy', '건강한', 133),
        ('sick', '아픈', 134),
        ('rich', '부유한', 135),
        ('clever', '영리한', 136),
        ('stupid', '멍청한', 137),
        ('kind', '친절한', 138),
        ('cruel', '잔인한', 139),
        ('honest', '정직한', 140),
        ('brave', '용감한', 141),
        ('careful', '조심스러운', 142),
        ('careless', '부주의한', 143),
        ('polite', '공손한', 144),
        ('rude', '무례한', 145),
        ('patient', '참을성 있는', 146),
        ('lazy', '게으른', 147),
        ('active', '활동적인', 148),
        ('creative', '창의적인', 149),
        ('curious', '호기심 많은', 150),
        ('confident', '자신감 있는', 151),
        ('nervous', '긴장한', 152),
        ('calm', '침착한', 153),
        ('proud', '자랑스러운', 154),
        ('ashamed', '부끄러운', 155),
        ('grateful', '고마워하는', 156),
        ('lucky', '운이 좋은', 157),
        ('strange', '이상한', 158),
        ('normal', '정상적인', 159),
        ('usual', '평소의', 160),
        ('unusual', '특이한', 161),
        ('impossible', '불가능한', 162),
        ('probable', '있을 법한', 163),
        ('obvious', '명백한', 164),
        ('specific', '구체적인', 165),
        ('basic', '기초적인', 166),
        ('advanced', '고급의', 167),
        ('complex', '복잡한', 168),
        ('complete', '완전한', 169),
        ('incomplete', '불완전한', 170),
        ('correct', '올바른', 171),
        ('accurate', '정확한', 172),
        ('exact', '정확한', 173),
        ('approximate', '대략의', 174),
        ('direct', '직접적인', 175),
        ('indirect', '간접적인', 176),
        ('positive', '긍정적인', 177),
        ('negative', '부정적인', 178),
        ('passive', '수동적인', 179),
        ('formal', '격식 있는', 180),
        ('informal', '비격식의', 181),
        ('official', '공식적인', 182),
        ('temporary', '일시적인', 183),
        ('permanent', '영구적인', 184),
        ('frequent', '빈번한', 185),
        ('rare', '드문', 186),
        ('sudden', '갑작스러운', 187),
        ('gradual', '점진적인', 188),
        ('rapid', '급속한', 189),
        ('steady', '꾸준한', 190),
        ('stable', '안정적인', 191),
        ('unstable', '불안정한', 192),
        ('flexible', '유연한', 193),
        ('rigid', '경직된', 194),
        ('efficient', '효율적인', 195),
        ('effective', '효과적인', 196),
        ('practical', '실용적인', 197),
        ('theoretical', '이론적인', 198),
        ('real', '실제의', 199),
        ('virtual', '가상의', 200),
        ('digital', '디지털의', 201),
        ('analog', '아날로그의', 202),
        ('global', '세계적인', 203),
        ('national', '국가의', 204),
        ('urban', '도시의', 205),
        ('rural', '시골의', 206),
        ('indoor', '실내의', 207),
        ('outdoor', '야외의', 208),
        ('online', '온라인의', 209),
        ('offline', '오프라인의', 210),
        ('visible', '보이는', 211),
        ('invisible', '보이지 않는', 212),
        ('unavailable', '이용 불가능한', 213),
        ('reliable', '믿을 수 있는', 214),
        ('convenient', '편리한', 215),
        ('comfortable', '편안한', 216),
        ('dangerous', '위험한', 217),
        ('harmful', '해로운', 218),
        ('helpful', '도움이 되는', 219),
        ('painful', '고통스러운', 220),
        ('powerful', '강력한', 221),
        ('peaceful', '평화로운', 222),
        ('wonderful', '훌륭한', 223),
        ('terrible', '끔찍한', 224),
        ('awful', '형편없는', 225),
        ('amazing', '놀라운', 226),
        ('exciting', '신나는', 227),
        ('boring', '지루한', 228),
        ('funny', '재미있는', 229),
        ('urgent', '긴급한', 230),
        ('essential', '필수적인', 231),
        ('optional', '선택적인', 232),
        ('relevant', '관련 있는', 233),
        ('suitable', '적합한', 234),
        ('appropriate', '적절한', 235),
        ('adequate', '충분한', 236),
        ('insufficient', '불충분한', 237),
        ('equal', '동등한', 238),
        ('unequal', '불평등한', 239),
        ('fair', '공정한', 240),
        ('unfair', '불공정한', 241),
        ('illegal', '불법의', 242),
        ('secure', '안전한', 243),
        ('insecure', '불안전한', 244),
        ('aware', '알고 있는', 245),
        ('unaware', '모르는', 246),
        ('familiar', '익숙한', 247),
        ('unfamiliar', '낯선', 248),
        ('original', '원래의 / 독창적인', 249),
        ('unique', '독특한', 250),
        ('ordinary', '평범한', 251),
        ('extraordinary', '비범한', 252),
        ('bright', '밝은 / 똑똑한', 253),
        ('broad', '넓은', 254),
        ('narrow', '좁은', 255),
        ('deep', '깊은', 256),
        ('shallow', '얕은', 257),
        ('thick', '두꺼운', 258),
        ('thin', '얇은', 259),
        ('sharp', '날카로운', 260),
        ('smooth', '매끄러운', 261),
        ('rough', '거친', 262),
        ('tight', '꽉 끼는', 263),
        ('loose', '헐거운', 264),
        ('solid', '단단한', 265),
        ('liquid', '액체의', 266),
        ('raw', '날것의', 267),
        ('ripe', '익은', 268),
        ('sour', '신', 269),
        ('sweet', '달콤한', 270),
        ('bitter', '쓴', 271),
        ('salty', '짠', 272),
        ('spicy', '매운', 273),
        ('tasty', '맛있는', 274),
        ('delicious', '아주 맛있는', 275),
        ('ugly', '못생긴', 276),
        ('pretty', '예쁜', 277),
        ('handsome', '잘생긴', 278),
        ('cute', '귀여운', 279),
        ('elegant', '우아한', 280),
        ('messy', '지저분한', 281),
        ('neat', '단정한', 282),
        ('tidy', '깔끔한', 283),
        ('crowded', '붐비는', 284),
        ('silent', '고요한', 285),
        ('loud', '큰 소리의', 286),
        ('gentle', '온화한', 287),
        ('harsh', '가혹한', 288),
        ('mild', '온화한 / 순한', 289),
        ('severe', '심각한', 290),
        ('extreme', '극단적인', 291),
        ('moderate', '적당한', 292),
        ('absolute', '절대적인', 293),
        ('relative', '상대적인', 294),
        ('internal', '내부의', 295),
        ('external', '외부의', 296),
        ('primary', '일차적인', 297),
        ('secondary', '이차적인', 298),
        ('senior', '상급의', 299),
        ('junior', '하급의', 300),
        ('previous', '이전의', 301),
        ('following', '다음의', 302),
        ('annual', '해마다의', 303),
        ('daily', '매일의', 304),
        ('weekly', '매주의', 305),
        ('monthly', '매월의', 306),
        ('instant', '즉각적인', 307),
        ('delayed', '지연된', 308),
        ('automatic', '자동의', 309),
        ('manual', '수동의', 310),
        ('mobile', '이동식의', 311),
        ('portable', '휴대용의', 312),
        ('wireless', '무선의', 313),
        ('wired', '유선의', 314),
        ('compatible', '호환되는', 315),
        ('independent', '독립적인', 316),
        ('dependent', '의존적인', 317),
        ('responsible', '책임 있는', 318),
        ('irresponsible', '무책임한', 319),
        ('reasonable', '합리적인', 320),
        ('unreasonable', '불합리한', 321),
        ('sensitive', '민감한', 322),
        ('sensible', '분별 있는', 323),
        ('emotional', '감정적인', 324),
        ('logical', '논리적인', 325),
        ('critical', '비판적인 / 중대한', 326),
        ('typical', '전형적인', 327),
        ('ideal', '이상적인', 328),
        ('perfect', '완벽한', 329),
        ('flawed', '결점 있는', 330),
        ('broken', '고장난 / 깨진', 331),
        ('fixed', '고정된 / 수리된', 332),
        ('updated', '갱신된', 333),
        ('outdated', '구식의', 334),
        ('obsolete', '폐기된', 335),
        ('innovative', '혁신적인', 336)
) AS v(front, back, ord)
WHERE d.name = '영어 · 기초 형용사' AND d.source_type = 'BUILTIN';
INSERT INTO decks (name, owner_id, source_type, sort_order)
VALUES ('일본어 · N5 한자', NULL, 'BUILTIN', 130);

INSERT INTO cards (deck_id, front_text, back_text, sort_order)
SELECT d.id, v.front, v.back, v.ord
FROM decks d
CROSS JOIN (
    VALUES
        ('一', E'いち・いつ / ひと・ひとつ\n하나, 일', 1),
        ('二', E'に / ふた・ふたつ\n둘, 이', 2),
        ('三', E'さん / み・みっつ\n셋, 삼', 3),
        ('四', E'し / よ・よん・よっつ\n넷, 사', 4),
        ('五', E'ご / いつ・いつつ\n다섯, 오', 5),
        ('六', E'ろく / む・むっつ\n여섯, 육', 6),
        ('七', E'しち / なな・ななつ\n일곱, 칠', 7),
        ('八', E'はち / や・やっつ\n여덟, 팔', 8),
        ('九', E'きゅう・く / ここの・ここのつ\n아홉, 구', 9),
        ('十', E'じゅう / とお\n열, 십', 10),
        ('百', E'ひゃく / —\n백', 11),
        ('千', E'せん / ち\n천', 12),
        ('万', E'まん / —\n만', 13),
        ('円', E'えん / —\n엔(화폐), 원', 14),
        ('日', E'にち・じつ / ひ・か\n해, 날, 일', 15),
        ('月', E'げつ・がつ / つき\n달, 월', 16),
        ('火', E'か / ひ\n불, 화', 17),
        ('水', E'すい / みず\n물, 수', 18),
        ('木', E'もく・ぼく / き\n나무, 목', 19),
        ('金', E'きん・こん / かね\n금, 돈', 20),
        ('土', E'ど・と / つち\n흙, 토', 21),
        ('曜', E'よう / —\n요일의 요', 22),
        ('今', E'こん / いま\n지금, 금', 23),
        ('週', E'しゅう / —\n주(週)', 24),
        ('年', E'ねん / とし\n해, 년', 25),
        ('時', E'じ / とき\n때, 시', 26),
        ('間', E'かん・けん / あいだ・ま\n사이, 간', 27),
        ('分', E'ぶん・ふん・ぶ / わ・わける\n나누다, 분', 28),
        ('半', E'はん / なかば\n반, 절반', 29),
        ('午', E'ご / —\n낮, 오(午)', 30),
        ('前', E'ぜん / まえ\n앞, 전', 31),
        ('後', E'ご・こう / あと・うし・のち\n뒤, 후', 32),
        ('上', E'じょう / うえ・あ・のぼ\n위, 상', 33),
        ('下', E'か・げ / した・さ・くだ・お\n아래, 하', 34),
        ('中', E'ちゅう / なか\n가운데, 중', 35),
        ('外', E'がい / そと・はず\n밖, 외', 36),
        ('左', E'さ / ひだり\n왼쪽, 좌', 37),
        ('右', E'う・ゆう / みぎ\n오른쪽, 우', 38),
        ('東', E'とう / ひがし\n동(東)', 39),
        ('西', E'せい・さい / にし\n서(西)', 40),
        ('南', E'なん / みなみ\n남(南)', 41),
        ('北', E'ほく / きた\n북(北)', 42),
        ('人', E'じん・にん / ひと\n사람, 인', 43),
        ('男', E'だん・なん / おとこ\n남자, 남', 44),
        ('女', E'じょ・にょ / おんな・め\n여자, 여', 45),
        ('子', E'し・す / こ\n아이, 자', 46),
        ('父', E'ふ / ちち・とう\n아버지, 부', 47),
        ('母', E'ぼ / はは・かあ\n어머니, 모', 48),
        ('友', E'ゆう / とも\n친구, 우', 49),
        ('名', E'めい・みょう / な\n이름, 명', 50),
        ('先', E'せん / さき\n먼저, 선', 51),
        ('生', E'せい・しょう / い・う・は\n살다, 생', 52),
        ('学', E'がく / まな\n배우다, 학', 53),
        ('校', E'こう / —\n학교, 교', 54),
        ('本', E'ほん / もと\n책, 본', 55),
        ('語', E'ご / かた\n말, 어', 56),
        ('読', E'どく / よ\n읽다, 독', 57),
        ('書', E'しょ / か\n쓰다, 서', 58),
        ('聞', E'ぶん / き\n듣다, 문', 59),
        ('話', E'わ / はな・はなし\n이야기하다, 화', 60),
        ('見', E'けん / み\n보다, 견', 61),
        ('行', E'こう・ぎょう / い・ゆ・おこな\n가다, 행', 62),
        ('来', E'らい / く・きた\n오다, 래', 63),
        ('帰', E'き / かえ\n돌아가다, 귀', 64),
        ('入', E'にゅう / はい・い\n들어가다, 입', 65),
        ('出', E'しゅつ / で・だ\n나가다, 출', 66),
        ('休', E'きゅう / やす\n쉬다, 휴', 67),
        ('食', E'しょく / た・く\n먹다, 식', 68),
        ('飲', E'いん / の\n마시다, 음', 69),
        ('買', E'ばい / か\n사다, 매', 70),
        ('売', E'ばい / う\n팔다, 매', 71),
        ('電', E'でん / —\n전기, 전', 72),
        ('車', E'しゃ / くるま\n수레, 차', 73),
        ('駅', E'えき / —\n역', 74),
        ('社', E'しゃ / やしろ\n회사, 사', 75),
        ('会', E'かい・え / あ\n모이다, 회', 76),
        ('国', E'こく / くに\n나라, 국', 77),
        ('山', E'さん・ざん / やま\n산', 78),
        ('川', E'せん / かわ\n강, 천', 79),
        ('田', E'でん / た\n논, 전', 80),
        ('天', E'てん / あま・あめ\n하늘, 천', 81),
        ('気', E'き・け / —\n기운, 기', 82),
        ('雨', E'う / あめ・あま\n비, 우', 83),
        ('雪', E'せつ / ゆき\n눈, 설', 84),
        ('大', E'だい・たい / おお\n크다, 대', 85),
        ('小', E'しょう / ちい・こ・お\n작다, 소', 86),
        ('高', E'こう / たか\n높다, 고', 87),
        ('安', E'あん / やす\n싸다, 편안, 안', 88),
        ('新', E'しん / あたら・あら\n새롭다, 신', 89),
        ('古', E'こ / ふる\n오래되다, 고', 90),
        ('長', E'ちょう / なが\n길다, 장', 91),
        ('短', E'たん / みじか\n짧다, 단', 92),
        ('多', E'た / おお\n많다, 다', 93),
        ('少', E'しょう / すく・すこ\n적다, 소', 94),
        ('白', E'はく・びゃく / しろ・しら\n하양, 백', 95),
        ('黒', E'こく / くろ\n검정, 흑', 96),
        ('赤', E'せき / あか\n빨강, 적', 97),
        ('青', E'せい・しょう / あお\n파랑, 청', 98),
        ('好', E'こう / す・この\n좋아하다, 호', 99),
        ('何', E'か / なに・なん\n무엇, 하', 100),
        ('毎', E'まい / —\n마다, 매', 101),
        ('口', E'こう・く / くち\n입, 구', 102),
        ('目', E'もく・ぼく / め\n눈, 목', 103),
        ('耳', E'じ / みみ\n귀, 이', 104),
        ('手', E'しゅ / て\n손, 수', 105),
        ('足', E'そく / あし・た\n발, 족', 106),
        ('立', E'りつ / た\n서다, 립', 107),
        ('待', E'たい / ま\n기다리다, 대', 108),
        ('持', E'じ / も\n가지다, 지', 109),
        ('道', E'どう・とう / みち\n길, 도', 110),
        ('私', E'し / わたし・わたくし\n나, 사', 111),
        ('店', E'てん / みせ\n가게, 점', 112),
        ('員', E'いん / —\n직원, 원', 113),
        ('病', E'びょう / や・やまい\n병', 114),
        ('院', E'いん / —\n원(병원 등)', 115),
        ('医', E'い / —\n의(醫)', 116),
        ('勉', E'べん / —\n힘쓰다, 면', 117),
        ('強', E'きょう・ごう / つよ・し\n강하다, 강', 118),
        ('漢', E'かん / —\n한(漢)', 119),
        ('字', E'じ / あざ\n글자, 자', 120),
        ('文', E'ぶん・もん / ふみ\n글, 문', 121),
        ('英', E'えい / —\n영(英)', 122),
        ('薬', E'やく / くすり\n약', 123),
        ('肉', E'にく / —\n고기, 육', 124),
        ('魚', E'ぎょ / うお・さかな\n물고기, 어', 125),
        ('茶', E'ちゃ・さ / —\n차', 126),
        ('花', E'か / はな\n꽃, 화', 127),
        ('空', E'くう / そら・あ・から\n하늘, 비다, 공', 128),
        ('海', E'かい / うみ\n바다, 해', 129),
        ('屋', E'おく / や\n집, 옥', 130),
        ('所', E'しょ / ところ\n곳, 소', 131),
        ('方', E'ほう / かた\n방향, 분(方)', 132),
        ('朝', E'ちょう / あさ\n아침, 조', 133),
        ('昼', E'ちゅう / ひる\n낮, 주', 134),
        ('夜', E'や / よ・よる\n밤, 야', 135),
        ('晩', E'ばん / —\n저녁, 만', 136)
) AS v(front, back, ord)
WHERE d.name = '일본어 · N5 한자' AND d.source_type = 'BUILTIN';
