# UN members + common extras (대만, 바티칸).
# (country_ko, country_en, capital_ko, capital_en)

WORLD_CAPITALS = [
    ("가나", "Ghana", "아크라", "Accra"),
    ("가봉", "Gabon", "리브르빌", "Libreville"),
    ("가이아나", "Guyana", "조지타운", "Georgetown"),
    ("감비아", "Gambia", "반줄", "Banjul"),
    ("과테말라", "Guatemala", "과테말라시티", "Guatemala City"),
    ("그레나다", "Grenada", "세인트조지스", "St. George's"),
    ("그리스", "Greece", "아테네", "Athens"),
    ("기니", "Guinea", "코나크리", "Conakry"),
    ("기니비사우", "Guinea-Bissau", "비사우", "Bissau"),
    ("나미비아", "Namibia", "빈트후크", "Windhoek"),
    ("나우루", "Nauru", "야렌", "Yaren"),
    ("나이지리아", "Nigeria", "아부자", "Abuja"),
    ("남수단", "South Sudan", "주바", "Juba"),
    ("남아프리카공화국", "South Africa", "프리토리아", "Pretoria"),
    ("네덜란드", "Netherlands", "암스테르담", "Amsterdam"),
    ("네팔", "Nepal", "카트만두", "Kathmandu"),
    ("노르웨이", "Norway", "오슬로", "Oslo"),
    ("뉴질랜드", "New Zealand", "웰링턴", "Wellington"),
    ("니제르", "Niger", "니아메", "Niamey"),
    ("니카라과", "Nicaragua", "마나과", "Managua"),
    ("대한민국", "South Korea", "서울", "Seoul"),
    ("덴마크", "Denmark", "코펜하겐", "Copenhagen"),
    ("도미니카공화국", "Dominican Republic", "산토도밍고", "Santo Domingo"),
    ("도미니카연방", "Dominica", "로조", "Roseau"),
    ("독일", "Germany", "베를린", "Berlin"),
    ("동티모르", "Timor-Leste", "딜리", "Dili"),
    ("라오스", "Laos", "비엔티안", "Vientiane"),
    ("라이베리아", "Liberia", "몬로비아", "Monrovia"),
    ("라트비아", "Latvia", "리가", "Riga"),
    ("러시아", "Russia", "모스크바", "Moscow"),
    ("레바논", "Lebanon", "베이루트", "Beirut"),
    ("레소토", "Lesotho", "마세루", "Maseru"),
    ("루마니아", "Romania", "부쿠레슈티", "Bucharest"),
    ("룩셈부르크", "Luxembourg", "룩셈부르크", "Luxembourg"),
    ("르완다", "Rwanda", "키갈리", "Kigali"),
    ("리비아", "Libya", "트리폴리", "Tripoli"),
    ("리투아니아", "Lithuania", "빌뉴스", "Vilnius"),
    ("리히텐슈타인", "Liechtenstein", "파두츠", "Vaduz"),
    ("마다가스카르", "Madagascar", "안타나나리보", "Antananarivo"),
    ("마셜제도", "Marshall Islands", "마주로", "Majuro"),
    ("말라위", "Malawi", "릴롱궤", "Lilongwe"),
    ("말레이시아", "Malaysia", "쿠알라룸푸르", "Kuala Lumpur"),
    ("말리", "Mali", "바마코", "Bamako"),
    ("멕시코", "Mexico", "멕시코시티", "Mexico City"),
    ("모나코", "Monaco", "모나코", "Monaco"),
    ("모로코", "Morocco", "라바트", "Rabat"),
    ("모리셔스", "Mauritius", "포트루이스", "Port Louis"),
    ("모리타니", "Mauritania", "누악쇼트", "Nouakchott"),
    ("모잠비크", "Mozambique", "마푸토", "Maputo"),
    ("몬테네그로", "Montenegro", "포드고리차", "Podgorica"),
    ("몰도바", "Moldova", "키시너우", "Chișinău"),
    ("몰디브", "Maldives", "말레", "Malé"),
    ("몰타", "Malta", "발레타", "Valletta"),
    ("몽골", "Mongolia", "울란바토르", "Ulaanbaatar"),
    ("미국", "United States", "워싱턴 D.C.", "Washington, D.C."),
    ("미얀마", "Myanmar", "네피도", "Naypyidaw"),
    ("미크로네시아", "Micronesia", "팔리키르", "Palikir"),
    ("바누아투", "Vanuatu", "포트빌라", "Port Vila"),
    ("바레인", "Bahrain", "마나마", "Manama"),
    ("바베이도스", "Barbados", "브리지타운", "Bridgetown"),
    ("바티칸", "Vatican City", "바티칸", "Vatican City"),
    ("바하마", "Bahamas", "나소", "Nassau"),
    ("방글라데시", "Bangladesh", "다카", "Dhaka"),
    ("베냉", "Benin", "포르토노보", "Porto-Novo"),
    ("베네수엘라", "Venezuela", "카라카스", "Caracas"),
    ("베트남", "Vietnam", "하노이", "Hanoi"),
    ("벨기에", "Belgium", "브뤼셀", "Brussels"),
    ("벨라루스", "Belarus", "민스크", "Minsk"),
    ("벨리즈", "Belize", "벨모판", "Belmopan"),
    ("보스니아헤르체고비나", "Bosnia and Herzegovina", "사라예보", "Sarajevo"),
    ("보츠와나", "Botswana", "가보로네", "Gaborone"),
    ("볼리비아", "Bolivia", "라파스", "La Paz"),
    ("부룬디", "Burundi", "기테가", "Gitega"),
    ("부르키나파소", "Burkina Faso", "와가두구", "Ouagadougou"),
    ("부탄", "Bhutan", "팀부", "Thimphu"),
    ("북마케도니아", "North Macedonia", "스코페", "Skopje"),
    ("북한", "North Korea", "평양", "Pyongyang"),
    ("불가리아", "Bulgaria", "소피아", "Sofia"),
    ("브라질", "Brazil", "브라질리아", "Brasília"),
    ("브루나이", "Brunei", "반다르스리브가완", "Bandar Seri Begawan"),
    ("사모아", "Samoa", "아피아", "Apia"),
    ("사우디아라비아", "Saudi Arabia", "리야드", "Riyadh"),
    ("산마리노", "San Marino", "산마리노", "San Marino"),
    ("상투메프린시페", "São Tomé and Príncipe", "상투메", "São Tomé"),
    ("세네갈", "Senegal", "다카르", "Dakar"),
    ("세르비아", "Serbia", "베오그라드", "Belgrade"),
    ("세이셸", "Seychelles", "빅토리아", "Victoria"),
    ("세인트루시아", "Saint Lucia", "캐스트리스", "Castries"),
    ("세인트빈센트그레나딘", "Saint Vincent and the Grenadines", "킹스타운", "Kingstown"),
    ("세인트키츠네비스", "Saint Kitts and Nevis", "바스테르", "Basseterre"),
    ("소말리아", "Somalia", "모가디슈", "Mogadishu"),
    ("솔로몬제도", "Solomon Islands", "호니아라", "Honiara"),
    ("수단", "Sudan", "하르툼", "Khartoum"),
    ("수리남", "Suriname", "파라마리보", "Paramaribo"),
    ("스리랑카", "Sri Lanka", "스리자야와르데네푸라코테", "Sri Jayawardenepura Kotte"),
    ("스웨덴", "Sweden", "스톡홀름", "Stockholm"),
    ("스위스", "Switzerland", "베른", "Bern"),
    ("스페인", "Spain", "마드리드", "Madrid"),
    ("슬로바키아", "Slovakia", "브라티슬라바", "Bratislava"),
    ("슬로베니아", "Slovenia", "류블랴나", "Ljubljana"),
    ("시리아", "Syria", "다마스쿠스", "Damascus"),
    ("시에라리온", "Sierra Leone", "프리타운", "Freetown"),
    ("싱가포르", "Singapore", "싱가포르", "Singapore"),
    ("아랍에미리트", "United Arab Emirates", "아부다비", "Abu Dhabi"),
    ("아르메니아", "Armenia", "예레반", "Yerevan"),
    ("아르헨티나", "Argentina", "부에노스아이레스", "Buenos Aires"),
    ("아이슬란드", "Iceland", "레이캬비크", "Reykjavík"),
    ("아이티", "Haiti", "포르토프랭스", "Port-au-Prince"),
    ("아일랜드", "Ireland", "더블린", "Dublin"),
    ("아제르바이잔", "Azerbaijan", "바쿠", "Baku"),
    ("아프가니스탄", "Afghanistan", "카불", "Kabul"),
    ("안도라", "Andorra", "안도라라베야", "Andorra la Vella"),
    ("알바니아", "Albania", "티라나", "Tirana"),
    ("알제리", "Algeria", "알제", "Algiers"),
    ("앙골라", "Angola", "루안다", "Luanda"),
    ("앤티가바부다", "Antigua and Barbuda", "세인트존스", "Saint John's"),
    ("에리트레아", "Eritrea", "아스마라", "Asmara"),
    ("에스와티니", "Eswatini", "음바바네", "Mbabane"),
    ("에스토니아", "Estonia", "탈린", "Tallinn"),
    ("에콰도르", "Ecuador", "키토", "Quito"),
    ("에티오피아", "Ethiopia", "아디스아바바", "Addis Ababa"),
    ("엘살바도르", "El Salvador", "산살바도르", "San Salvador"),
    ("영국", "United Kingdom", "런던", "London"),
    ("예멘", "Yemen", "사나", "Sana'a"),
    ("오만", "Oman", "무스카트", "Muscat"),
    ("오스트리아", "Austria", "빈", "Vienna"),
    ("온두라스", "Honduras", "테구시갈파", "Tegucigalpa"),
    ("요르단", "Jordan", "암만", "Amman"),
    ("우간다", "Uganda", "캄팔라", "Kampala"),
    ("우루과이", "Uruguay", "몬테비데오", "Montevideo"),
    ("우즈베키스탄", "Uzbekistan", "타슈켄트", "Tashkent"),
    ("우크라이나", "Ukraine", "키이우", "Kyiv"),
    ("이라크", "Iraq", "바그다드", "Baghdad"),
    ("이란", "Iran", "테헤란", "Tehran"),
    ("이스라엘", "Israel", "예루살렘", "Jerusalem"),
    ("이집트", "Egypt", "카이로", "Cairo"),
    ("이탈리아", "Italy", "로마", "Rome"),
    ("인도", "India", "뉴델리", "New Delhi"),
    ("인도네시아", "Indonesia", "자카르타", "Jakarta"),
    ("일본", "Japan", "도쿄", "Tokyo"),
    ("자메이카", "Jamaica", "킹스턴", "Kingston"),
    ("잠비아", "Zambia", "루사카", "Lusaka"),
    ("적도기니", "Equatorial Guinea", "말라보", "Malabo"),
    ("조지아", "Georgia", "트빌리시", "Tbilisi"),
    ("중국", "China", "베이징", "Beijing"),
    ("중앙아프리카공화국", "Central African Republic", "방기", "Bangui"),
    ("지부티", "Djibouti", "지부티", "Djibouti"),
    ("짐바브웨", "Zimbabwe", "하라레", "Harare"),
    ("차드", "Chad", "은자메나", "N'Djamena"),
    ("체코", "Czechia", "프라하", "Prague"),
    ("칠레", "Chile", "산티아고", "Santiago"),
    ("카메룬", "Cameroon", "야운데", "Yaoundé"),
    ("카보베르데", "Cabo Verde", "프라이아", "Praia"),
    ("카자흐스탄", "Kazakhstan", "아스타나", "Astana"),
    ("카타르", "Qatar", "도하", "Doha"),
    ("캄보디아", "Cambodia", "프놈펜", "Phnom Penh"),
    ("캐나다", "Canada", "오타와", "Ottawa"),
    ("케냐", "Kenya", "나이로비", "Nairobi"),
    ("코모로", "Comoros", "모로니", "Moroni"),
    ("코소보", "Kosovo", "프리슈티나", "Pristina"),
    ("코스타리카", "Costa Rica", "산호세", "San José"),
    ("코트디부아르", "Côte d'Ivoire", "야무수크로", "Yamoussoukro"),
    ("콜롬비아", "Colombia", "보고타", "Bogotá"),
    ("콩고공화국", "Republic of the Congo", "브라자빌", "Brazzaville"),
    ("콩고민주공화국", "DR Congo", "킨샤사", "Kinshasa"),
    ("쿠바", "Cuba", "아바나", "Havana"),
    ("쿠웨이트", "Kuwait", "쿠웨이트시티", "Kuwait City"),
    ("크로아티아", "Croatia", "자그레브", "Zagreb"),
    ("키르기스스탄", "Kyrgyzstan", "비슈케크", "Bishkek"),
    ("키리바시", "Kiribati", "타라와", "Tarawa"),
    ("키프로스", "Cyprus", "니코시아", "Nicosia"),
    ("타지키스탄", "Tajikistan", "두샨베", "Dushanbe"),
    ("탄자니아", "Tanzania", "도도마", "Dodoma"),
    ("태국", "Thailand", "방콕", "Bangkok"),
    ("대만", "Taiwan", "타이베이", "Taipei"),
    ("튀르키예", "Türkiye", "앙카라", "Ankara"),
    ("토고", "Togo", "로메", "Lomé"),
    ("통가", "Tonga", "누쿠알로파", "Nuku'alofa"),
    ("투르크메니스탄", "Turkmenistan", "아시가바트", "Ashgabat"),
    ("투발루", "Tuvalu", "푸나푸티", "Funafuti"),
    ("튀니지", "Tunisia", "튀니스", "Tunis"),
    ("트리니다드토바고", "Trinidad and Tobago", "포트오브스페인", "Port of Spain"),
    ("파나마", "Panama", "파나마시티", "Panama City"),
    ("파라과이", "Paraguay", "아순시온", "Asunción"),
    ("파키스탄", "Pakistan", "이슬라마바드", "Islamabad"),
    ("파푸아뉴기니", "Papua New Guinea", "포트모르즈비", "Port Moresby"),
    ("팔라우", "Palau", "은게룰무드", "Ngerulmud"),
    ("페루", "Peru", "리마", "Lima"),
    ("포르투갈", "Portugal", "리스본", "Lisbon"),
    ("폴란드", "Poland", "바르샤바", "Warsaw"),
    ("프랑스", "France", "파리", "Paris"),
    ("피지", "Fiji", "수바", "Suva"),
    ("핀란드", "Finland", "헬싱키", "Helsinki"),
    ("필리핀", "Philippines", "마닐라", "Manila"),
    ("헝가리", "Hungary", "부다페스트", "Budapest"),
    ("호주", "Australia", "캔버라", "Canberra"),
]
